### ISSUE TITLE
undefined method `empty?' for nil:NilClass in progress_formatter.rb

### ISSUE THREAD

**Issue by DavidEGrayson** [bbatsov/rubocop#1642]
There seems to be a bug in Rubocop 0.29.0.  I am running it on Arch Linux 64-bit with Ruby 2.2.0.

To reproduce the bug, I made a new directory that just contains a `.rubocop.yml` file with the following contents:

````yml
AllCops:
  Exclude:
    - **/*_old.rb
````

Then I ran `rubocop` (with no options) at the command line and it produced the following output:

````
undefined method `empty?' for nil:NilClass
/home/david/.gem/ruby/2.2.0/gems/rubocop-0.29.0/lib/rubocop/formatter/progress_formatter.rb:28:in `finished'
/home/david/.gem/ruby/2.2.0/gems/rubocop-0.29.0/lib/rubocop/formatter/formatter_set.rb:28:in `block (3 levels) in <class:FormatterSet>'
/home/david/.gem/ruby/2.2.0/gems/rubocop-0.29.0/lib/rubocop/formatter/formatter_set.rb:28:in `each'
/home/david/.gem/ruby/2.2.0/gems/rubocop-0.29.0/lib/rubocop/formatter/formatter_set.rb:28:in `block (2 levels) in <class:FormatterSet>'
/home/david/.gem/ruby/2.2.0/gems/rubocop-0.29.0/lib/rubocop/runner.rb:46:in `ensure in run'
/home/david/.gem/ruby/2.2.0/gems/rubocop-0.29.0/lib/rubocop/runner.rb:47:in `run'
/home/david/.gem/ruby/2.2.0/gems/rubocop-0.29.0/lib/rubocop/cli.rb:24:in `run'
/home/david/.gem/ruby/2.2.0/gems/rubocop-0.29.0/bin/rubocop:13:in `block in <top (required)>'
/opt/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/david/.gem/ruby/2.2.0/gems/rubocop-0.29.0/bin/rubocop:12:in `<top (required)>'
/home/david/.gem/ruby/2.2.0/bin/rubocop:23:in `load'
/home/david/.gem/ruby/2.2.0/bin/rubocop:23:in `<main>'
````

**Comment by askreet** [comment]
I see this behavior with master on OS X, Ruby 2.1.5.  Running with 0.27.1, I see a different error:
```
(<unknown>): did not find expected alphabetic or numeric character while scanning an alias at line 3 column 7
/Users/kyle.smith/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych.rb:370:in `parse'
/Users/kyle.smith/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
/Users/kyle.smith/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych.rb:318:in `parse'
/Users/kyle.smith/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych.rb:245:in `load'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/gems/rubocop-0.27.1/lib/rubocop/config_loader.rb:34:in `load_file'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/gems/rubocop-0.27.1/lib/rubocop/config_loader.rb:93:in `configuration_from_file'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/gems/rubocop-0.27.1/lib/rubocop/config_store.rb:40:in `for'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/gems/rubocop-0.27.1/lib/rubocop/target_finder.rb:62:in `target_files_in_dir'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/gems/rubocop-0.27.1/lib/rubocop/target_finder.rb:31:in `find'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/gems/rubocop-0.27.1/lib/rubocop/runner.rb:47:in `find_target_files'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/gems/rubocop-0.27.1/lib/rubocop/runner.rb:18:in `run'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/gems/rubocop-0.27.1/lib/rubocop/cli.rb:24:in `run'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/gems/rubocop-0.27.1/bin/rubocop:13:in `block in <top (required)>'
/Users/kyle.smith/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/gems/rubocop-0.27.1/bin/rubocop:12:in `<top (required)>'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/bin/rubocop:23:in `load'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/bin/rubocop:23:in `<main>'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/kyle.smith/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

It seems as though you have to quote a string like **/*_old.rb in YAML, though the error could be more helpful as it used to be.

**Comment by bquorning** [comment]
It took some digging around, but I think I found it: The `ensure` call added in ece834eabe0a189e8b06654d33338aae944792a6 doesn’t allow the `Psych::SyntaxError` raised by `YAML.load` in https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/config_loader.rb#L117 to walk all the way up to https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cli.rb#L32-L35 as it previously did.

cc @jonas054

**Comment by bquorning** [comment]
And yes, the SyntaxError exception is caused by `**/*_old.rb` not being quoted. This config file should word:
```yml
AllCops:
  Exclude:
    - "**/*_old.rb"
```

**Comment by jonas054** [comment]
@bquorning Exactly. We get a second exception inside the `ensure` block, which is why the original exception is lost. This could be solved by adding a `begin` and `end` inside `Runner#run`. The only problem is that we'll overstep the `MethodLength` by doing so.

I don't have time to fix this myself, going on vacation tomorrow, so I'd be grateful if someone could submit a PR.

**Comment by bquorning** [comment]
@jonas054 There’s a PR here: #1643.

**Comment by jonas054** [comment]
@bquorning Nice! I see that you and @bbatsov are working out the details. Looks good!
