### ISSUE TITLE
Error in Performance/Sample cop 0.30.1

### ISSUE THREAD

**Issue by axlekb** [bbatsov/rubocop#1827]
Just tried upgrading to 0.30.1, but ran into this error with one of my files:

```
An error occurred while Performance/Sample cop was inspecting <filename>
undefined method `selector' for #<Parser::Source::Map::Variable:0x007fb924c54740>
/Users/alexb/.rvm/gems/ruby-2.2.1/gems/rubocop-0.30.1/lib/rubocop/cop/performance/sample.rb:37:in `on_send'
(eval):5:in `block (2 levels) in on_send'
/Users/alexb/.rvm/gems/ruby-2.2.1/gems/rubocop-0.30.1/lib/rubocop/cop/commissioner.rb:92:in `with_cop_error_handling'
(eval):4:in `block in on_send'
(eval):2:in `each'
(eval):2:in `on_send'
/Users/alexb/.rvm/gems/ruby-2.2.1/gems/ast-2.0.0/lib/ast/processor.rb:239:in `process'
/Users/alexb/.rvm/gems/ruby-2.2.1/gems/parser-2.2.2.1/lib/parser/ast/processor.rb:42:in `on_vasgn'
/Users/alexb/.rvm/gems/ruby-2.2.1/gems/parser-2.2.2.1/lib/parser/ast/processor.rb:47:in `process_var_asgn_node'
```

**Comment by bbatsov** [comment]
Can you add here some code that triggers the error? Feel free to obfuscate it if it's something sensitive.

**Comment by axlekb** [comment]
Whoops, sorry, that was lazy.  I'll do some binary code deletion to find the triggering code.  I'll get back to you in a bit.

**Comment by rrosenblum** [comment]
I am hoping that this has already been fixed, in master, by the other issues reported for this cop.

**Comment by axlekb** [comment]
Thanks, fixed in `master`.
