### ISSUE TITLE
Performance/Sample bug with #shuffle

### ISSUE THREAD

**Issue by dziemba** [bbatsov/rubocop#1838]
Running the latest rubocop on the following code:

```ruby
def m
  [1].shuffle
end
```

causes an error:

```
1 error occurred:
An error occurred while Performance/Sample cop was inspecting test.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.30.1 (using Parser 2.2.2.1, running on ruby 2.2.1 x86_64-darwin14)
```

**Comment by RobinDaugherty** [comment]
I'm also having the same issue. Tested with MRI 2.1.4, 2.1.6, and 2.2.2. If the file contains nothing more than "shuffle" I get this error. Here's the trace:

```
undefined method `selector' for nil:NilClass
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/cop/performance/sample.rb:37:in `on_send'
(eval):5:in `block (2 levels) in on_send'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/cop/commissioner.rb:92:in `with_cop_error_handling'
(eval):4:in `block in on_send'
(eval):2:in `each'
(eval):2:in `on_send'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.0.0/lib/ast/processor.rb:239:in `process'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/cop/commissioner.rb:52:in `investigate'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/cop/team.rb:33:in `inspect_file'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:129:in `inspect_file'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:100:in `block in do_inspection_loop'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:94:in `loop'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:94:in `do_inspection_loop'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:72:in `process_file'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:53:in `block in inspect_files'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:51:in `each'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:51:in `inspect_files'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:30:in `run'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/lib/rubocop/cli.rb:24:in `run'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/bin/rubocop:13:in `block in <top (required)>'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.30.1/bin/rubocop:12:in `<top (required)>'
/usr/local/var/rbenv/versions/2.2.2/bin/rubocop:23:in `load'
/usr/local/var/rbenv/versions/2.2.2/bin/rubocop:23:in `<main>'
```

**Comment by bbatsov** [comment]
Try the `master` branch.

**Comment by ryanbjones** [comment]
I ran into this same issue including having it pointed at the master branch.  
The code that causes the error is
`random_batch = batch.shuffle(:random => ::Random.new(seed))`

From RuboCop:
```2 errors occurred:
An error occurred while Performance/Sample cop was inspecting /Users/ryanbjones/Desktop/sherlock/lib/sherlock/metrics/naive_bayes_test.rb.
An error occurred while Performance/Sample cop was inspecting /Users/ryanbjones/Desktop/sherlock/lib/sherlock/metrics/random_test.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.31.0 (using Parser 2.2.2.2, running on jruby 1.9.3 java)```

**Comment by jonas054** [comment]
Confirmed that there's still a bug. Reopening.

**Comment by rrosenblum** [comment]
I was unable to reproduce this in master. Is this issue still happening for anyone?

**Comment by dcarneiro** [comment]
it looks like it's fixed.

I had the same problem with this file:

```ruby
class Example
  def test
    [1, 2, 3, 4, 3].shuffle
  end
end
```

```
$rubocop -a example.rb
Inspecting 1 file
An error occurred while Performance/Sample cop was inspecting 
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.30.1 (using Parser 2.2.2.2, running on ruby 2.2.2 x86_64-darwin14)
```

After I updated to 0.31.0 it worked fine

```
$ gem update rubocop
Fetching: rubocop-0.31.0.gem (100%)
```

:heart::heart::heart:
