### ISSUE TITLE
Performance/Sample breaks on all calls to shuffle

### ISSUE THREAD

**Issue by m1foley** [bbatsov/rubocop#1861]
`Performance/Sample` seems to break on all calls to `shuffle` -- even if we're not calling `shuffle.first` which is what it's supposed to check for. 

Here's my file (it breaks on more complex/realistic scenarios as well):

```
$ cat hi.rb
bar.shuffle
```

Backtrace:

```
$ rubocop -d hi.rb
Inspecting 1 file
Scanning /Users/mike/temp/hi.rb
For /Users/mike/temp: configuration from /Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/config/default.yml
Inheriting configuration from /Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/config/enabled.yml
Inheriting configuration from /Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/config/disabled.yml
An error occurred while Performance/Sample cop was inspecting /Users/mike/temp/hi.rb.
undefined method `selector' for nil:NilClass
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/cop/performance/sample.rb:37:in `on_send'
(eval):5:in `block (2 levels) in on_send'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/cop/commissioner.rb:92:in `with_cop_error_handling'
(eval):4:in `block in on_send'
(eval):2:in `each'
(eval):2:in `on_send'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:239:in `process'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/cop/commissioner.rb:52:in `investigate'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/cop/team.rb:33:in `inspect_file'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:129:in `inspect_file'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:100:in `block in do_inspection_loop'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:94:in `loop'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:94:in `do_inspection_loop'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:72:in `process_file'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:53:in `block in inspect_files'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:51:in `each'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:51:in `inspect_files'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/runner.rb:30:in `run'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/cli.rb:24:in `run'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/bin/rubocop:13:in `block in <top (required)>'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/Users/mike/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/bin/rubocop:12:in `<top (required)>'
/Users/mike/.rbenv/versions/2.1.6/bin/rubocop:23:in `load'
/Users/mike/.rbenv/versions/2.1.6/bin/rubocop:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Performance/Sample cop was inspecting /Users/mike/temp/hi.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.30.1 (using Parser 2.2.2.2, running on ruby 2.1.6 x86_64-darwin14.0)
Finished in 0.024731 seconds
```

**Comment by m1foley** [comment]
In this example I don't have a `.rubocop.yml` file.

**Comment by rrosenblum** [comment]
This bug has already been fixed in master. 

Sorry for the inconvenience, and thank you for reporting the bug.

**Comment by m1foley** [comment]
I can confirm that this is fixed in master. Hopefully it will get pushed to Rubygems soon. Thanks!
