### ISSUE TITLE
Rubocop errors with "private method `select' called for nil:NilClass"

### ISSUE THREAD

**Issue by jkrmr** [bbatsov/rubocop#1867]
I'm getting some error messages on Ruby 2.1.6. 

```

% rubocop config/routes.rb
Inspecting 1 file
An error occurred while Style/FileName cop was inspecting ~/Desktop/project/config/routes.rb.
To see the complete backtrace run rubocop -d.
C

[. . . ]

1 error occurred:

An error occurred while Style/FileName cop was inspecting ~/Desktop/project/config/routes.rb.

Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.31.0 (using Parser 2.2.2.2, running on ruby 2.1.6 x86_64-darwin14.0)
```

```
% rubocop -d

For ~/Desktop/project: configuration from ~/.rubocop.yml
Default configuration from ~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/config/default.yml
Inheriting configuration from ~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/config/enabled.yml
Inheriting configuration from ~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/config/disabled.yml

private method 'select' called for nil:NilClass
~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:113:in 'excluded_dirs'
~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:90:in 'find_files'
~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:60:in 'target_files_in_dir'
~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:31:in 'find'
~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/lib/rubocop/runner.rb:41:in 'find_target_files'
~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/lib/rubocop/runner.rb:29:in 'run'
~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/lib/rubocop/cli.rb:26:in 'run'
~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/bin/rubocop:13:in 'block in <top (required)>'
~/.rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in 'realtime'
~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rubocop-0.31.0/bin/rubocop:12:in '<top (required)>'
~/.rbenv/versions/2.1.6/bin/rubocop:23:in 'load'
~/.rbenv/versions/2.1.6/bin/rubocop:23:in '<main>'
~/.rbenv/versions/2.1.6/bin/ruby_executable_hooks:15:in 'eval'
~/.rbenv/versions/2.1.6/bin/ruby_executable_hooks:15:in '<main>'
Finished in 0.018387 seconds


```

**Comment by jkrmr** [comment]
This was caused by overriding `Exclude` incorrectly:

```yaml
AllCops:
  Exclude:
```

Fixed by deleting the `Exclude:` line.

**Comment by AlexWayfer** [comment]
I've got this error in CI.

My `AllCops` config is:

```yaml
AllCops:
  NewCops: enable
  Exclude:
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
      - <%= path.sub(/^!! /, '') %>
    <% end %>
```

So, it's not "empty", but I guess the command can return zero entries.

Locally it works:

```
> git status --ignored --porcelain
 M .gitignore
!! config/database.yaml
!! config/deploy.yaml
!! config/logging.yaml
!! config/main.yaml
!! config/systemd.service
!! db/
!! node_modules/
!! package-lock.json
```

But it's a dynamic list, and in CI there are no such files (they're not required for RuboCop), and I guess I have to wrap `Exclude:` into something like `<% if ENV['CI'] %>`.
