### ISSUE TITLE
rubocop v0.29.1 crashed when auto-correct hash with double splat (**)

### ISSUE THREAD

**Issue by JuanitoFatas** [bbatsov/rubocop#1926]
Given this file:

```ruby
Hash(foo: 'bar',
  **extra_params
)
```

when you run: `bundle exec rubocop -DR --auto-correct`, will yield errors:

```
$ rcc null/example.rb
Inspecting 1 file

0 files inspected, no offenses detected
undefined method `loc' for nil:NilClass
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/cop/style/align_hash.rb:239:in `block in autocorrect'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/cop/corrector.rb:46:in `call'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/cop/corrector.rb:46:in `block in rewrite'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/cop/corrector.rb:45:in `each'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/cop/corrector.rb:45:in `rewrite'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/cop/team.rb:83:in `autocorrect_one_cop'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/cop/team.rb:65:in `autocorrect'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/cop/team.rb:35:in `inspect_file'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/runner.rb:129:in `inspect_file'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/runner.rb:100:in `block in do_inspection_loop'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/runner.rb:94:in `loop'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/runner.rb:94:in `do_inspection_loop'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/runner.rb:72:in `process_file'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/runner.rb:53:in `block in inspect_files'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/runner.rb:51:in `each'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/runner.rb:51:in `inspect_files'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/runner.rb:30:in `run'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/lib/rubocop/cli.rb:24:in `run'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/bin/rubocop:13:in `block in <top (required)>'
/Users/Juan/.rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/Juan/.gem/ruby/2.2.2/gems/rubocop-0.29.1/bin/rubocop:12:in `<top (required)>'
/Users/Juan/.gem/ruby/2.2.2/bin/rubocop:23:in `load'
/Users/Juan/.gem/ruby/2.2.2/bin/rubocop:23:in `<main>'
```

And for some reason, I cannot upgrade my rubocop (locked at v0.29.1) :sweat: 

Any pointers on how could I fix this? Thanks!

**Comment by jonas054** [comment]
The problem is still present on the current `master`.
