### ISSUE TITLE
Rubocop not working -- not sure why...

### ISSUE THREAD

**Issue by robbyoconnor** [bbatsov/rubocop#2055]
This is failing in `2.2.2`

```
$ rubocop
(<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
/home/rob/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse'
/home/rob/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
/home/rob/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:318:in `parse'
/home/rob/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:284:in `safe_load'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/config_loader.rb:129:in `yaml_safe_load'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/config_loader.rb:117:in `load_yaml_configuration'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/config_loader.rb:27:in `load_file'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/config_loader.rb:85:in `configuration_from_file'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/config_store.rb:40:in `for'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/target_finder.rb:112:in `excluded_dirs'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/target_finder.rb:90:in `find_files'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/target_finder.rb:60:in `target_files_in_dir'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/target_finder.rb:31:in `find'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/runner.rb:41:in `find_target_files'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/runner.rb:29:in `run'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/lib/rubocop/cli.rb:26:in `run'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/bin/rubocop:13:in `block in <top (required)>'
/home/rob/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/rob/.rvm/gems/ruby-2.2.2/gems/rubocop-0.32.1/bin/rubocop:12:in `<top (required)>'
/home/rob/.rvm/gems/ruby-2.2.2/bin/rubocop:23:in `load'
/home/rob/.rvm/gems/ruby-2.2.2/bin/rubocop:23:in `<main>'
/home/rob/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/home/rob/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by robbyoconnor** [comment]
Okay -- There was an error in my `.rubocop.yml` file -- disregard
