### ISSUE TITLE
Parse error "instance_exec {}"

### ISSUE THREAD

**Issue by akicho8** [bbatsov/rubocop#2165]
rubocop version 0.33.0

> $ echo "instance_exec {}" > a.rb
> $ rubocop -d a.rb
> warning: parser/current is loading parser/ruby22, which recognizes
> warning: 2.2.3-compliant syntax, but you are running 2.2.2.
> Inspecting 1 file
> Scanning /private/tmp/a.rb
> For /private/tmp: configuration from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/config/default.yml
> Inheriting configuration from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/config/enabled.yml
> Inheriting configuration from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/config/disabled.yml
> An error occurred while Style/Alias cop was inspecting /private/tmp/a.rb.
> undefined method `each_node' for nil:NilClass
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/cop/style/alias.rb:19:in `on_block'
> (eval):5:in `block (2 levels) in on_block'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/cop/commissioner.rb:92:in `with_cop_error_handling'
> (eval):4:in `block in on_block'
> (eval):2:in `each'
> (eval):2:in `on_block'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/cop/commissioner.rb:52:in `investigate'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/cop/team.rb:33:in `inspect_file'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:135:in `inspect_file'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:106:in `block in do_inspection_loop'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:100:in `loop'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:100:in `do_inspection_loop'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:78:in `process_file'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:53:in `block in inspect_files'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:51:in `each'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:51:in `inspect_files'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:30:in `run'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/lib/rubocop/cli.rb:26:in `run'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/bin/rubocop:13:in `block in <top (required)>'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
> /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.33.0/bin/rubocop:12:in `<top (required)>'
> /usr/local/var/rbenv/versions/2.2.2/bin/rubocop:23:in `load'
> /usr/local/var/rbenv/versions/2.2.2/bin/rubocop:23:in `<main>'
> .
> 
> 1 file inspected, no offenses detected
> 
> 1 error occurred: 
> An error occurred while Style/Alias cop was inspecting /private/tmp/a.rb.
> Errors are usually caused by RuboCop bugs.
> Please, report your problems to RuboCop's issue tracker.
> Mention the following information in the issue report: 
> 0.33.0 (using Parser 2.3.0.pre.2, running on ruby 2.2.2 x86_64-darwin13)
> Finished in 0.16178937209770083 seconds

**Comment by akicho8** [comment]
Thanks :+1:
