### ISSUE TITLE
private method `load' called for Psych:Module

### ISSUE THREAD

**Issue by jcoyne** [bbatsov/rubocop#2417]
```
$ rubocop
private method `load' called for Psych:Module
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/config_loader.rb:163:in `yaml_safe_load'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/config_loader.rb:145:in `load_yaml_configuration'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/config_loader.rb:28:in `load_file'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/config_loader.rb:92:in `configuration_from_file'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/config_store.rb:40:in `for'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/target_finder.rb:112:in `excluded_dirs'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/target_finder.rb:90:in `find_files'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/target_finder.rb:60:in `target_files_in_dir'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/target_finder.rb:31:in `find'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:46:in `find_target_files'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:30:in `run'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/cli.rb:26:in `run'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/bin/rubocop:13:in `block in <top (required)>'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/bin/rubocop:12:in `<top (required)>'
/Users/justin/.rbenv/versions/2.2.3/bin/rubocop:23:in `load'
/Users/justin/.rbenv/versions/2.2.3/bin/rubocop:23:in `<main>'
```

**Comment by jcoyne** [comment]
This looks a lot like #1510 I have Psych 2.0.15

**Comment by jcoyne** [comment]
Fixed by running `gem update --system`
