### ISSUE TITLE
undefined method `begin' for #<Parser::Source::Map::Variable:0x00000001f113b8> when apply auto-correct 

### ISSUE THREAD

**Issue by mguthmuller** [bbatsov/rubocop#2482]
Hi,

I've got this error when i enable auto-correct with the and/or style rule

```
undefined method `begin' for #<Parser::Source::Map::Variable:0x00000003779ba8>
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/style/and_or.rb:113:in `correctable_send?'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/style/and_or.rb:95:in `correct_send'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/style/and_or.rb:67:in `block (2 levels) in correction'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/style/and_or.rb:65:in `each'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/style/and_or.rb:65:in `block in correction'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:46:in `call'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:46:in `block in rewrite'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:45:in `each'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:45:in `rewrite'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:91:in `autocorrect_one_cop'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:66:in `autocorrect'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:36:in `inspect_file'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:190:in `inspect_file'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:157:in `block in do_inspection_loop'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `loop'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `do_inspection_loop'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:93:in `process_file'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:58:in `block in inspect_files'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `each'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `inspect_files'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/runner.rb:34:in `run'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/lib/rubocop/cli.rb:26:in `run'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/bin/rubocop:13:in `block in <top (required)>'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/lib/gems/2.1.0/gems/rubocop-0.35.1/bin/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>'
```

Rubocop version : 0.35.1

To reproduce the issue :

```
echo 'h={}; p h if !h or h.empty?' | rubocop --stdin --only Style/AndOr --auto-correct -
```

There is no issue if I change the condition by removing the not (!) : p h if h or h.empty? 
There is no issue if I put parentheses around conditions : p h if (!h) or (h.empty?)

**Comment by alexdowad** [comment]
Thanks for the nice, concise repro!

**Comment by alexdowad** [comment]
This was my bug. Thanks for finding it! I just opened a PR with a fix.
