### ISSUE TITLE
Rubocop error with 

### ISSUE THREAD

**Issue by dmoran-epages** [bbatsov/rubocop#2530]
Blah.test("1" => "one")

    Style/BracesAroundHashParameters:  
      EnforcedStyle: context

1 error occurred:
An error occurred while Style/BracesAroundHashParameters cop was inspecting /home/declan/tmp/rubytst/rubytst.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.35.1 (using Parser 2.2.3.0, running on ruby 2.2.3 x86_64-linux)
Finished in 0.10173707800095144 seconds

**Comment by alexdowad** [comment]
`rubocop -d`, please.

**Comment by dmoran-epages** [comment]
````
declan@linux-p8rr:~/tmp/rubytst> rubocop -d --display-cop-names --rails --extra-details --format html -o rubocop.html 
For /home/declan/tmp/rubytst: configuration from /home/declan/tmp/rubytst/.rubocop.yml
Default configuration from /home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/config/default.yml
Inheriting configuration from /home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/config/enabled.yml
Inheriting configuration from /home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/config/disabled.yml
Scanning /home/declan/tmp/rubytst/rubytst.rb
An error occurred while Style/BracesAroundHashParameters cop was inspecting /home/declan/tmp/rubytst/rubytst.rb.
Unknown style context selected!
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/mixin/configurable_enforced_style.rb:82:in `style'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/style/braces_around_hash_parameters.rb:31:in `check'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/style/braces_around_hash_parameters.rb:25:in `on_send'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:37:in `block (2 levels) in on_send'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:87:in `with_cop_error_handling'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:36:in `block in on_send'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:34:in `each'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:34:in `on_send'
/home/declan/.gem/ruby/2.2.3/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:53:in `investigate'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:34:in `inspect_file'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:190:in `inspect_file'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:157:in `block in do_inspection_loop'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `loop'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `do_inspection_loop'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:93:in `process_file'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:58:in `block in inspect_files'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `each'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `inspect_files'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:34:in `run'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/lib/rubocop/cli.rb:26:in `run'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/bin/rubocop:13:in `block in <top (required)>'
/home/declan/dev/web_framework/rails/ruby/2.2.3/lib64/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/declan/.gem/ruby/2.2.3/gems/rubocop-0.35.1/bin/rubocop:12:in `<top (required)>'
/home/declan/.gem/ruby/2.2.3/bin/rubocop:23:in `load'
/home/declan/.gem/ruby/2.2.3/bin/rubocop:23:in `<main>'                                                                                                                            
                                                                                                                                                                                   
1 error occurred:                                                                                                                                                                  
An error occurred while Style/BracesAroundHashParameters cop was inspecting /home/declan/tmp/rubytst/rubytst.rb.                                                                   
Errors are usually caused by RuboCop bugs.                                                                                                                                         
Please, report your problems to RuboCop's issue tracker.                                                                                                                           
Mention the following information in the issue report:                                                                                                                             
0.35.1 (using Parser 2.2.3.0, running on ruby 2.2.3 x86_64-linux)                                                                                                                  
Finished in 0.1387021669997921 seconds                                                                                                                                             
declan@linux-p8rr:~/tmp/rubytst>                                                           
````

**Comment by alexdowad** [comment]
OK. It's `context_dependent`, not `context`.

**Comment by dmoran-epages** [comment]
Thanks
