### ISSUE TITLE
Style/RescueEnsureAlignment cop fails when inspecting a file

### ISSUE THREAD

**Issue by texpert** [bbatsov/rubocop#2534]
Hello!

Rubocop raises an error - this is the debug output:

```
undefined method `loc' for nil:NilClass
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/style/rescue_ensure_alignment.rb:59:in `check'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/style/rescue_ensure_alignment.rb:28:in `on_resbody'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:37:in `block (2 levels) in on_resbody'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:87:in `with_cop_error_handling'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:36:in `block in on_resbody'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:34:in `each'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:34:in `on_resbody'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_rescue'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_module'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:53:in `investigate'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:34:in `inspect_file'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/runner.rb:190:in `inspect_file'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/runner.rb:157:in `block in do_inspection_loop'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `loop'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `do_inspection_loop'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/runner.rb:93:in `process_file'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/runner.rb:58:in `block in inspect_files'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `each'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `inspect_files'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/runner.rb:34:in `run'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/lib/rubocop/cli.rb:26:in `run'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/bin/rubocop:13:in `block in <top (required)>'
/home/thunder/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/thunder/.rvm/gems/ruby-2.1.7/gems/rubocop-0.35.1/bin/rubocop:12:in `<top (required)>'
/home/thunder/.rvm/gems/ruby-2.1.7/bin/rubocop:23:in `load'
/home/thunder/.rvm/gems/ruby-2.1.7/bin/rubocop:23:in `<main>'
/home/thunder/.rvm/gems/ruby-2.1.7/bin/ruby_executable_hooks:15:in `eval'
/home/thunder/.rvm/gems/ruby-2.1.7/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by alexdowad** [comment]
Can you post a small excerpt of the code which causes this error?

It should be a `rescue` clause which is not associated with a `begin..end` or `def..end` block.

**Comment by texpert** [comment]
Yes, it's like this:
```
module SomeModule
  mattr_accessor :attr1, :attr2

... some code

rescue StandardError => e
  Rails.logger.info"'Error occured: #{e}"
end

**Comment by alexdowad** [comment]
Aha, interesting.

**Comment by alexdowad** [comment]
Just pushed a fix to my open PR.
