### ISSUE TITLE
Rubocop fails in auto-correct mode

### ISSUE THREAD

**Issue by MrWEST** [bbatsov/rubocop#2635]
When I'm try to run Rubocop in auto-correct mode I got this error:

~~~
Parser::Source::Rewriter detected clobbering
/gems/parser-2.2.3.0/lib/parser/source/rewriter.rb:177:in `append'
/gems/parser-2.2.3.0/lib/parser/source/rewriter.rb:86:in `replace'
/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:80:in `replace'
/gems/rubocop-0.35.1/lib/rubocop/cop/style/rescue_modifier.rb:38:in `block in autocorrect'
/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:46:in `call'
/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:46:in `block in rewrite'
/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:45:in `each'
/gems/rubocop-0.35.1/lib/rubocop/cop/corrector.rb:45:in `rewrite'
/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:91:in `autocorrect_one_cop'
/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:66:in `autocorrect'
/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:36:in `inspect_file'
/gems/rubocop-0.35.1/lib/rubocop/runner.rb:190:in `inspect_file'
/gems/rubocop-0.35.1/lib/rubocop/runner.rb:157:in `block in do_inspection_loop'
/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `loop'
/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `do_inspection_loop'
/gems/rubocop-0.35.1/lib/rubocop/runner.rb:93:in `process_file'
/gems/rubocop-0.35.1/lib/rubocop/runner.rb:58:in `block in inspect_files'
/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `each'
/gems/rubocop-0.35.1/lib/rubocop/runner.rb:56:in `inspect_files'
/gems/rubocop-0.35.1/lib/rubocop/runner.rb:34:in `run'
/gems/rubocop-0.35.1/lib/rubocop/cli.rb:26:in `run'
/gems/rubocop-0.35.1/bin/rubocop:13:in `block in <top (required)>'
/ruby/2.2.0/benchmark.rb:303:in `realtime'
/gems/rubocop-0.35.1/bin/rubocop:12:in `<top (required)>'
/bin/rubocop:23:in `load'
/bin/rubocop:23:in `<main>'
/bin/ruby_executable_hooks:15:in `eval'
/bin/ruby_executable_hooks:15:in `<main>'
~~~

By excluding files from auto-correct, I have found a line which falls Rubocop:

    @current_school = @current_listing.role.schools.find(params[:school_id]) rescue @current_listing.role.schools.find(cookies[:school_id]) rescue nil

I refactored this code manually to this version and everything is running okay:

~~~
@current_school = begin
  @current_listing.role.schools.find(params[:school_id])
rescue
  @current_listing.role.schools.find(cookies[:school_id]) rescue nil
end
~~~

Rubocop version:

    0.35.1 (using Parser 2.2.3.0, running on ruby 2.2.3 x86_64-darwin15)

**Comment by alexdowad** [comment]
This is fixed on `master`. The only problem I see is that `RescueModifier` messes up the indentation of the code, and other cops don't correct that bad indentation.

**Comment by alexdowad** [comment]
Just opening a PR which fixes the trouble with indentation. Then this can be closed.

**Comment by alexdowad** [comment]
This is already fixed. Please close.
