### ISSUE TITLE
Performance/Casecmp autocorrect fails sometimes

### ISSUE THREAD

**Issue by maxjacobson** [bbatsov/rubocop#2637]
```ruby
# dogs.rb
class Dog
  attr_reader :name

  def initialize(name)
    @name = name
  end

  def matches?(other)
    name.downcase == other.name.downcase
  end
end

dog = Dog.new("Milo")
other_dog = Dog.new("milo")
puts dog.matches?(other_dog)
```

when I run `ruby dogs.rb` I get "true"

when I run `rubocop -a -d dogs.rb` it fails with this exception:

```
undefined method `begin_pos' for nil:NilClass
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/performance/casecmp.rb:35:in `autocorrect'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/cop.rb:179:in `correct'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/cop.rb:169:in `add_offense'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/performance/casecmp.rb:27:in `block in on_send'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/performance/casecmp.rb:21:in `downcase_eq'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/performance/casecmp.rb:25:in `on_send'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:38:in `block (2 levels) in on_send'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:88:in `with_cop_error_handling'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:37:in `block in on_send'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:35:in `each'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:35:in `on_send'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/max/.gem/ruby/2.3.0/gems/parser-2.3.0.0/lib/parser/ast/processor.rb:125:in `on_def'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_def'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/max/.gem/ruby/2.3.0/gems/parser-2.3.0.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_begin'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/max/.gem/ruby/2.3.0/gems/parser-2.3.0.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_class'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/max/.gem/ruby/2.3.0/gems/parser-2.3.0.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_begin'
/home/max/.gem/ruby/2.3.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:54:in `investigate'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cop/team.rb:37:in `inspect_file'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:194:in `inspect_file'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:164:in `block in do_inspection_loop'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `loop'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `do_inspection_loop'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:87:in `process_file'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `each'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `inspect_files'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:35:in `run'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/lib/rubocop/cli.rb:30:in `run'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/bin/rubocop:14:in `block in <top (required)>'
/home/max/.rubies/2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/max/.gem/ruby/2.3.0/gems/rubocop-0.36.0/bin/rubocop:13:in `<top (required)>'
bin/rubocop:16:in `load'
bin/rubocop:16:in `<main>'
```

**Comment by thorsteneckel** [comment]
Same issue over here (rubocop-0.36.0). Cop even leaves broken code behind.

Code like:
```ruby
    name.downcase == other.name.downcase
```

ls left behind as:
```ruby
    name.casecmp(other.name)
````

Instead of:
```ruby
    name.casecmp(other.name).zero?
````

**Comment by bbatsov** [comment]
Fixed on `master`.
