### ISSUE TITLE
Style/MutableConstant causes undefined method `loc' for nil:NilClass

### ISSUE THREAD

**Issue by aevernon** [bbatsov/rubocop#2658]
If I call `rubocop -d` on this code:

```ruby
FOO, BAR = call_func
```

I get this error:

```
For /home/aev/test: configuration from /home/aev/.gem/ruby/gems/rubocop-0.36.0/config/default.yml
Inheriting configuration from /home/aev/.gem/ruby/gems/rubocop-0.36.0/config/enabled.yml
Inheriting configuration from /home/aev/.gem/ruby/gems/rubocop-0.36.0/config/disabled.yml
Inspecting 1 file
Scanning /home/aev/test/test.rb
An error occurred while Style/MutableConstant cop was inspecting /home/aev/test/test.rb.
undefined method `loc' for nil:NilClass
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/cop.rb:159:in `add_offense'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/style/mutable_constant.rb:24:in `on_casgn'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:38:in `block (2 levels) in on_casgn'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:88:in `with_cop_error_handling'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:37:in `block in on_casgn'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:35:in `each'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:35:in `on_casgn'
/home/aev/.gem/ruby/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/aev/.gem/ruby/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/aev/.gem/ruby/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/home/aev/.gem/ruby/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/aev/.gem/ruby/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_mlhs'
/home/aev/.gem/ruby/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/aev/.gem/ruby/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/aev/.gem/ruby/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/home/aev/.gem/ruby/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/aev/.gem/ruby/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_masgn'
/home/aev/.gem/ruby/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:54:in `investigate'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cop/team.rb:37:in `inspect_file'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/runner.rb:194:in `inspect_file'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/runner.rb:164:in `block in do_inspection_loop'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `loop'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `do_inspection_loop'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/runner.rb:87:in `process_file'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `each'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `inspect_files'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/runner.rb:35:in `run'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/lib/rubocop/cli.rb:30:in `run'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/bin/rubocop:14:in `block in <top (required)>'
/usr/share/ruby/benchmark.rb:303:in `realtime'
/home/aev/.gem/ruby/gems/rubocop-0.36.0/bin/rubocop:13:in `<top (required)>'
/home/aev/bin/rubocop:23:in `load'
/home/aev/bin/rubocop:23:in `<main>'
.

1 file inspected, no offenses detected

2 errors occurred:
An error occurred while Style/MutableConstant cop was inspecting /home/aev/test/test.rb.
An error occurred while Style/MutableConstant cop was inspecting /home/aev/test/test.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.36.0 (using Parser 2.3.0.1, running on ruby 2.2.4 x86_64-linux)
Finished in 0.0753912889995263 seconds
```

**Comment by bbatsov** [comment]
That's fixed on `master`.
