### ISSUE TITLE
Exception in Style/WordArray cop

### ISSUE THREAD

**Issue by tomhughes** [bbatsov/rubocop#2671]
Exception reported by the Style/WordArray cop - the invalid UTF-8 is a deliberate part of the test:

```
For /home/tom/src/osm/rails: configuration from /home/tom/src/osm/rails/.rubocop.yml
Inheriting configuration from /home/tom/src/osm/rails/.rubocop_todo.yml
Default configuration from /usr/local/share/gems/gems/rubocop-0.36.0/config/default.yml
Inheriting configuration from /usr/local/share/gems/gems/rubocop-0.36.0/config/enabled.yml
Inheriting configuration from /usr/local/share/gems/gems/rubocop-0.36.0/config/disabled.yml
Inspecting 1 file
Scanning /home/tom/src/osm/rails/test/models/message_test.rb
An error occurred while Style/WordArray cop was inspecting /home/tom/src/osm/rails/test/models/message_test.rb.
invalid byte sequence in UTF-8
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/style/word_array.rb:67:in `=~'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/style/word_array.rb:67:in `!~'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/style/word_array.rb:67:in `block in complex_content?'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/style/word_array.rb:65:in `any?'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/style/word_array.rb:65:in `complex_content?'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/style/word_array.rb:23:in `on_array'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:38:in `block (2 levels) in on_array'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:88:in `with_cop_error_handling'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:37:in `block in on_array'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:35:in `each'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:35:in `on_array'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/usr/local/share/gems/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:43:in `on_vasgn'
/usr/local/share/gems/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:49:in `process_var_asgn_node'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_lvasgn'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/usr/local/share/gems/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:9:in `process_regular_node'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_begin'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/usr/local/share/gems/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:125:in `on_def'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_def'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/usr/local/share/gems/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:9:in `process_regular_node'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_begin'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/usr/local/share/gems/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:9:in `process_regular_node'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_class'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/usr/local/share/gems/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:9:in `process_regular_node'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_begin'
/usr/local/share/gems/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:54:in `investigate'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cop/team.rb:37:in `inspect_file'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/runner.rb:194:in `inspect_file'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/runner.rb:164:in `block in do_inspection_loop'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `loop'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `do_inspection_loop'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/runner.rb:87:in `process_file'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `each'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `inspect_files'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/runner.rb:35:in `run'
/usr/local/share/gems/gems/rubocop-0.36.0/lib/rubocop/cli.rb:30:in `run'
/usr/local/share/gems/gems/rubocop-0.36.0/bin/rubocop:14:in `block in <top (required)>'
/usr/share/ruby/benchmark.rb:303:in `realtime'
/usr/local/share/gems/gems/rubocop-0.36.0/bin/rubocop:13:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Style/WordArray cop was inspecting /home/tom/src/osm/rails/test/models/message_test.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.36.0 (using Parser 2.3.0.1, running on ruby 2.2.4 x86_64-linux)
Finished in 0.2514732829295099 seconds
```

**Comment by oakbow** [comment]
It also happened to me.
Following is a sample code which causes this exception.

```rb
# app/helpers/application_helper.rb
  def hoge
    [
      ['FF5E', '301C']
    ]
  end
```

```
Inspecting 1 file
Scanning /Users/oakbow/projects/hogehoge/fugafuga/app/helpers/application_helper.rb
An error occurred while Style/WordArray cop was inspecting /Users/oakbow/projects/hogehoge/fugafuga/app/helpers/application_helper.rb.
comparison of Fixnum with String failed
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/style/word_array.rb:27:in `>='
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/style/word_array.rb:27:in `on_array'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:38:in `block (2 levels) in on_array'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:88:in `with_cop_error_handling'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:37:in `block in on_array'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:35:in `each'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:35:in `on_array'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:9:in `process_regular_node'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_array'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:125:in `on_def'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_def'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parser-2.3.0.1/lib/parser/ast/processor.rb:9:in `process_regular_node'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_module'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:54:in `investigate'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/team.rb:37:in `inspect_file'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:194:in `inspect_file'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:164:in `block in do_inspection_loop'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `loop'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `do_inspection_loop'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:87:in `process_file'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `each'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:35:in `run'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cli.rb:30:in `run'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/bin/rubocop:14:in `block in <top (required)>'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/oakbow/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/bin/rubocop:13:in `<top (required)>'
/Users/oakbow/.rbenv/versions/2.2.2/bin/rubocop:23:in `load'
/Users/oakbow/.rbenv/versions/2.2.2/bin/rubocop:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Style/WordArray cop was inspecting /Users/oakbow/projects/hogehogea/fugafuga/app/helpers/application_helper.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.36.0 (using Parser 2.3.0.1, running on ruby 2.2.2 x86_64-darwin13)
Finished in 0.1417672119969211 seconds
```

**Comment by alexdowad** [comment]
@oakbow Your code doesn't cause an exception for me on `master`.

**Comment by alexdowad** [comment]
@tomhughes Do you have a sample file which can be used to reproduce this problem on the latest release?

**Comment by tomhughes** [comment]
Sure - https://github.com/openstreetmap/openstreetmap-website/blob/master/test/models/message_test.rb is the file where I encountered it.

**Comment by alexdowad** [comment]
And you can still reproduce on v0.37?

**Comment by tomhughes** [comment]
Looks like it, yes.

**Comment by alexdowad** [comment]
OK, I'm all over it.
