### ISSUE TITLE
Performance/Casecmp auto-correct crashes

### ISSUE THREAD

**Issue by madwort** [bbatsov/rubocop#2727]
Here's one:

```
myothervar if myvar.downcase == myothervar
```
running `rubocop --auto-correct test1.rb` produces:
```
For /myprojectdirectory: configuration from /myprojectdirectory/.rubocop.yml
Inheriting configuration from /myprojectdirectory/.rubocop_todo.yml
Default configuration from /myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/config/default.yml
Inheriting configuration from /myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/config/enabled.yml
Inheriting configuration from /myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/config/disabled.yml
Inspecting 1 file
Scanning /myprojectdirectory/test1.rb
An error occurred while Performance/Casecmp cop was inspecting /myprojectdirectory/test1.rb.
undefined method `begin_pos' for nil:NilClass
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/performance/casecmp.rb:35:in `autocorrect'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/cop.rb:179:in `correct'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/cop.rb:169:in `add_offense'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/performance/casecmp.rb:27:in `block in on_send'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/performance/casecmp.rb:21:in `downcase_eq'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/performance/casecmp.rb:25:in `on_send'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:38:in `block (2 levels) in on_send'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:88:in `with_cop_error_handling'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:37:in `block in on_send'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:35:in `each'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:35:in `on_send'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `map'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:275:in `process_all'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/parser-2.3.0.2/lib/parser/ast/processor.rb:9:in `process_regular_node'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:42:in `on_if'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:54:in `investigate'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cop/team.rb:37:in `inspect_file'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:194:in `inspect_file'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:164:in `block in do_inspection_loop'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `loop'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `do_inspection_loop'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:87:in `process_file'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `each'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `inspect_files'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/runner.rb:35:in `run'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cli.rb:30:in `run'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/bin/rubocop:14:in `block in <top (required)>'
/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/gems/rubocop-0.36.0/bin/rubocop:13:in `<top (required)>'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/bin/rubocop:23:in `load'
/myprojectdirectory/vendor/bundle/ruby/2.2.0/bin/rubocop:23:in `<main>'
.
1 file inspected, no offenses detected

1 error occurred:
An error occurred while Performance/Casecmp cop was inspecting /home/tom/main/transportapi/transportapiv3/test1.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.36.0 (using Parser 2.3.0.2, running on ruby 2.2.2 x86_64-linux)
Finished in 0.1503763422369957 seconds

```

**Comment by madwort** [comment]
Here's another:

**Comment by madwort** [comment]
Hmm, but:
```
irb(main):004:0> myvar = "stuff"
=> "stuff"
irb(main):005:0> "Stuff".downcase == myvar
=> true
irb(main):006:0> "Stuff".casecmp(myvar)
=> 0
```

**Comment by madwort** [comment]
dupe of #2664 sorry for extra traffic. closing & commenting there.
