### ISSUE TITLE
Incompatible character encodings: UTF-8 and UTF-32LE

### ISSUE THREAD

**Issue by jottr** [bbatsov/rubocop#2751]
I am not sure if this issue is a function of a problem in the **parser** gem, or of **rubocop** itself. 
When running running `rubocop` I see the following error:

```bash
$ rubocop 
...
lib/tasks/comments.rake:40:1: C: Extra blank line detected.
lib/tasks/comments.rake:41:1: C: Extra blank line detected.
lib/tasks/comments.rake:42:1: C: Extra blank line detected.
lib/tasks/comments.rake:43:1: C: Extra blank line detected.
lib/tasks/comments.rake:43:1: C: Extra empty line detected at block body end.
lib/tasks/comments.rake:45:4: C: Final newline missing.
end

83 files inspected, 880 offenses detected
incompatible character encodings: UTF-8 and UTF-32LE
/usr/local/bundle/gems/parser-2.3.0.2/lib/parser/lexer/literal.rb:190:in `extend_string'
/usr/local/bundle/gems/parser-2.3.0.2/lib/parser/lexer.rb:15702:in `advance'
/usr/local/bundle/gems/parser-2.3.0.2/lib/parser/base.rb:219:in `next_token'
/usr/local/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
/usr/local/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
/usr/local/bundle/gems/parser-2.3.0.2/lib/parser/base.rb:162:in `parse'
/usr/local/bundle/gems/parser-2.3.0.2/lib/parser/base.rb:180:in `parse_with_comments'
/usr/local/bundle/gems/parser-2.3.0.2/lib/parser/base.rb:201:in `tokenize'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/processed_source.rb:92:in `parse'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/processed_source.rb:36:in `initialize'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/processed_source.rb:18:in `new'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/processed_source.rb:18:in `from_file'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/runner.rb:270:in `get_processed_source'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/runner.rb:86:in `process_file'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `each'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `inspect_files'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/runner.rb:35:in `run'
/usr/local/bundle/gems/rubocop-0.36.0/lib/rubocop/cli.rb:30:in `run'
/usr/local/bundle/gems/rubocop-0.36.0/bin/rubocop:14:in `block in <top (required)>'
/usr/local/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/usr/local/bundle/gems/rubocop-0.36.0/bin/rubocop:13:in `<top (required)>'
/usr/local/bundle/bin/rubocop:16:in `load'
/usr/local/bundle/bin/rubocop:16:in `<main>'
```

`ruby 2.1.2`

**Comment by alexdowad** [comment]
It's an issue with the `parser` gem for sure. I will look into it.

**Comment by alexdowad** [comment]
Can you send me a copy of the file which causes the error when inspected?

**Comment by jottr** [comment]
Sure
https://gist.github.com/jottr/3c81d89c1a763d247d06

**Comment by jottr** [comment]
​Could you be so kind and confirm that you received the gist? Thank you. :)​

2016-02-01 13:59 GMT+01:00 Jonas T. <j@ovvvo.co>:

> Sure
> https://gist.github.com/jottr/3c81d89c1a763d247d06
>
>
>


-- 


  _____ ____ ____ _____
 / _ \ V /\ V /\ V / _ \
 \___/\_/  \_/  \_/\___/



Please consider using Email encryption: keybase.io/jottr

**Comment by alexdowad** [comment]
Got it. Will check what the problem is later when I have time.

**Comment by alexdowad** [comment]
It seems that the problem isn't caused by that particular file. You are inspecting the entire "meingrundeinkommen" repo, is that right? Perhaps I can clone it and try inspecting it.

**Comment by jottr** [comment]
Yes I've simply run the rubocop on the master branch of [meingrundeinkommen](https://github.com/MeinGrundeinkommen/meingrundeinkommen) , even after changing the offending line in `comments.rake`, rubocop still crashed.

**Comment by alexdowad** [comment]
Just discovered a bug in `parser` which looks very similar to what you show here. Once a fix is merged and a new release made, I'll ask you to try again.

**Comment by alexdowad** [comment]
This should be fixed now.

**Comment by alexdowad** [comment]
Can you check on `master`?

**Comment by jottr** [comment]
Just checked. The issue seems to be fixed. Thank you!
