### ISSUE TITLE
Exception thrown while Performance/RedundantBlockCall cop was inspecting an empty method accepting ruby block as argument

### ISSUE THREAD

**Issue by yesuagg** [bbatsov/rubocop#2760]
Getting ```undefined method `each_node' for nil:NilClass``` exception while inspecting a file with empty method accepting block as one of the arguments.

somefile.rb
```
def foo(&block)
end
```

Exception trace:
```
$ rubocop somefile.rb -d
For /Users/yesuagg/project: configuration from /Users/yesuagg/project/.rubocop.yml
Inheriting configuration from /Users/yesuagg/project/.rubocop_todo.yml
Default configuration from /Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/config/default.yml
Inheriting configuration from /Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/config/enabled.yml
Inheriting configuration from /Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/config/disabled.yml
Inspecting 1 file
Scanning /Users/yesuagg/project/somefile.rb
An error occurred while Performance/RedundantBlockCall cop was inspecting /Users/yesuagg/project/somefile.rb.
undefined method `each_node' for nil:NilClass
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/performance/redundant_block_call.rb:36:in `blockarg_calls'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/performance/redundant_block_call.rb:40:in `block in on_def'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/performance/redundant_block_call.rb:30:in `blockarg_def'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/performance/redundant_block_call.rb:39:in `on_def'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:49:in `block (2 levels) in on_def'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:88:in `with_cop_error_handling'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:48:in `block in on_def'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:46:in `each'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:46:in `on_def'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/ast-2.2.0/lib/ast/processor/mixin.rb:259:in `process'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/commissioner.rb:54:in `investigate'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cop/team.rb:37:in `inspect_file'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/runner.rb:194:in `inspect_file'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/runner.rb:164:in `block in do_inspection_loop'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `loop'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/runner.rb:158:in `do_inspection_loop'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/runner.rb:87:in `process_file'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `each'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/runner.rb:35:in `run'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/lib/rubocop/cli.rb:30:in `run'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/bin/rubocop:14:in `block in <top (required)>'
/Users/yesuagg/.rvm/rubies/ruby-1.9.3-p125-perf/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/gems/rubocop-0.36.0/bin/rubocop:13:in `<top (required)>'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/bin/rubocop:23:in `load'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/bin/rubocop:23:in `<main>'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/bin/ruby_executable_hooks:15:in `eval'
/Users/yesuagg/.rvm/gems/ruby-1.9.3-p125-perf@cs/bin/ruby_executable_hooks:15:in `<main>'
```

Version info:
```
0.36.0 (using Parser 2.3.0.2, running on ruby 1.9.3 x86_64-darwin14.4.0)
```

**Comment by segiddins** [comment]
I believe this might be fixed on master?

**Comment by yesuagg** [comment]
@segiddins 
Yes, it is fixed on master. Thank you!
Any idea when will the next release be?
