### ISSUE TITLE
crush with  hash

### ISSUE THREAD

**Issue by kvokka** [bbatsov/rubocop#2817]
souse code is
```
    def create
      @item = model_name_helper.new(prepared_params(@param_name, @params_array))
      entity_params = params[item_symbol_helper]
      if @item.save
        @fields.each do |field, settings|
          case settings[:type]
            when :dual_list
              if settings[:show_in_card]
                values = entity_params ? entity_params[field] : nil   #code A
                if entity_params             #code B
                  values = entity_params[field] 
                  else
                  values =  nil
                end
                values&.each do |key, value|
                  settings[:recipient][:entity].create({settings[:recipient][:link_field] => @item.id, settings[:donor][:link_field] => key})
                end
              end
        end
    end
```

Crush with any typeA or typeB code.
Crushlog

```
                          ^^^^^^^^^^^

11 files inspected, 60 offenses detected
undefined method `type' for :values:Symbol
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:102:in `block in on_send'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:100:in `each'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:100:in `each_with_index'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:100:in `on_send'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_send'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:152:in `on_block'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_block'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:102:in `block in on_send'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:100:in `each'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:100:in `each_with_index'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:100:in `on_send'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_csend'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_begin'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:131:in `on_if'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_if'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_when'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:160:in `block in on_case'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:159:in `each'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:159:in `on_case'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_case'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:155:in `on_block'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_block'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_begin'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:131:in `on_if'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_if'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_begin'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:96:in `on_def'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_def'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_begin'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_module'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_begin'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_module'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:13:in `walk'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:56:in `investigate'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cop/team.rb:58:in `inspect_file'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/runner.rb:194:in `inspect_file'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/runner.rb:164:in `block in do_inspection_loop'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/runner.rb:158:in `loop'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/runner.rb:158:in `do_inspection_loop'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/runner.rb:87:in `process_file'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/runner.rb:57:in `each'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/runner.rb:57:in `inspect_files'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/runner.rb:35:in `run'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/lib/rubocop/cli.rb:30:in `run'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/bin/rubocop:14:in `block in <top (required)>'
/home/kvokka/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/kvokka/.rvm/gems/ruby-2.3.0/gems/rubocop-0.37.0/bin/rubocop:13:in `<top (required)>'
/home/kvokka/.rvm/gems/ruby-2.3.0/bin/rubocop:23:in `load'
/home/kvokka/.rvm/gems/ruby-2.3.0/bin/rubocop:23:in `<main>'
```

**Comment by alexdowad** [comment]
I can't reproduce this failure on `master`.

**Comment by kvokka** [comment]
sorry. I used 0.37 version.
with 0.37.1 all works good
