### ISSUE TITLE
Infinite loop correcting Style/SpaceAroundOperators

### ISSUE THREAD

**Issue by ggilder** [bbatsov/rubocop#2819]
Source to reproduce:

```ruby
attrs = {}
attrs[:foo], attrs[:bar] = call_some_method
attrs
```

Error looks like:

```
➤ ./bin/rubocop -D --auto-correct ~/Development/cbms/test.rb
Inspecting 1 file
C

Offenses:

/Users/gabriel/Development/cbms/test.rb:2:6: C: [Corrected] Style/SpaceAroundOperators: Surrounding space missing for operator [:foo].
attrs[:foo], attrs[:bar] = call_some_method
     ^^^^^^
/Users/gabriel/Development/cbms/test.rb:2:7: C: [Corrected] Style/SpaceAroundOperators: Surrounding space missing for operator [:foo].
attrs [:foo], attrs [:bar] = call_some_method
      ^^^^^^
/Users/gabriel/Development/cbms/test.rb:2:13: C: [Corrected] Style/SpaceBeforeComma: Space found before comma.
attrs [:foo] , attrs [:bar] = call_some_method
            ^
/Users/gabriel/Development/cbms/test.rb:2:19: C: [Corrected] Style/SpaceAroundOperators: Surrounding space missing for operator [:bar].
attrs[:foo], attrs[:bar] = call_some_method
                  ^^^^^^

0 files inspected, 4 offenses detected, 4 offenses corrected
/Users/gabriel/oss/rubocop/lib/rubocop/runner.rb:184:in `check_for_infinite_loop': Infinite loop detected in /Users/gabriel/Development/cbms/test.rb. (RuboCop::Runner::InfiniteCorrectionLoop)
    from /Users/gabriel/oss/rubocop/lib/rubocop/runner.rb:159:in `block in do_inspection_loop'
    from /Users/gabriel/oss/rubocop/lib/rubocop/runner.rb:158:in `loop'
    from /Users/gabriel/oss/rubocop/lib/rubocop/runner.rb:158:in `do_inspection_loop'
    from /Users/gabriel/oss/rubocop/lib/rubocop/runner.rb:87:in `process_file'
    from /Users/gabriel/oss/rubocop/lib/rubocop/runner.rb:59:in `block in inspect_files'
    from /Users/gabriel/oss/rubocop/lib/rubocop/runner.rb:57:in `each'
    from /Users/gabriel/oss/rubocop/lib/rubocop/runner.rb:57:in `inspect_files'
    from /Users/gabriel/oss/rubocop/lib/rubocop/runner.rb:35:in `run'
    from /Users/gabriel/oss/rubocop/lib/rubocop/cli.rb:30:in `run'
    from ./bin/rubocop:14:in `block in <main>'
    from /Users/gabriel/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
    from ./bin/rubocop:13:in `<main>'
```

**Comment by ggilder** [comment]
(Tested against 0.37.1 and master)

**Comment by alexdowad** [comment]
Just pushed a fix to my open PR.
