### ISSUE TITLE
Errno::ENAMETOOLONG: File name too long

### ISSUE THREAD

**Issue by bquorning** [bbatsov/rubocop#2822]
In the RuboCop repository, tag `v0.37.1`, I tried running RuboCop with the `--only` option and (too) many cop names:
```
» bin/rubocop --only MultilineBlockLayout,SpaceAroundKeyword,ConditionalAssignment,DuplicateMethods,SpaceAroundOperators,GuardClause,RedundantMatch,NestedMethodDefinition,TrailingUnderscoreVariable,WordArray
Inspecting 729 files


0 files inspected, no offenses detected
File name too long @ dir_s_mkdir - /private/var/folders/gy/lpk8yr8j5vl7ffd6nclth_4c0000gn/T/501/rubocop_cache/4ff67f03b0cdf946285544d9ccbebafa/_only_Style_MultilineBlockLayout_Style_SpaceAroundKeyword_Style_ConditionalAssignment_Lint_DuplicateMethods_Style_SpaceAroundOperators_Style_GuardClause_Performance_RedundantMatch_Lint_NestedMethodDefinition_Style_TrailingUnderscoreVariable_Style_WordArray_
/Users/bquorning/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir'
/Users/bquorning/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
/Users/bquorning/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
/Users/bquorning/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
/Users/bquorning/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
/Users/bquorning/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:211:in `each'
/Users/bquorning/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
/Users/bquorning/Code/rubocop/lib/rubocop/result_cache.rb:75:in `save'
/Users/bquorning/Code/rubocop/lib/rubocop/runner.rb:143:in `save_in_cache'
/Users/bquorning/Code/rubocop/lib/rubocop/runner.rb:89:in `process_file'
/Users/bquorning/Code/rubocop/lib/rubocop/runner.rb:59:in `block in inspect_files'
/Users/bquorning/Code/rubocop/lib/rubocop/runner.rb:57:in `each'
/Users/bquorning/Code/rubocop/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/bquorning/Code/rubocop/lib/rubocop/runner.rb:35:in `run'
/Users/bquorning/Code/rubocop/lib/rubocop/cli.rb:30:in `run'
bin/rubocop:14:in `block in <main>'
/Users/bquorning/.rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
bin/rubocop:13:in `<main>'
```

It looks like you were trying to create a folder with more than 255 characters in the name, which fails on HFS Plus and probably many other file systems.

**Comment by alexdowad** [comment]
Looks like @jonas054 wanted a separate cache for different combinations of CLI options (which makes sense).

To avoid this problem, a hash of the CLI options could be used, rather than concatenating them into a big string.

**Comment by alexdowad** [comment]
I have a fix for this, will open PR soon.
