### ISSUE TITLE
Out of char range error occurred.

### ISSUE THREAD

**Issue by krororo** [bbatsov/rubocop#2833]
The following code:

```ruby
foo = "\あ"
p foo
```

running rubocop:

~~~
$ rubocop /tmp/test.rb
Inspecting 1 file


0 files inspected, no offenses detected
12354 out of char range
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/parser-2.3.0.4/lib/parser/lexer.rb:20702:in `chr'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/parser-2.3.0.4/lib/parser/lexer.rb:20702:in `encode_escape'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/parser-2.3.0.4/lib/parser/lexer.rb:15601:in `advance'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/parser-2.3.0.4/lib/parser/base.rb:219:in `next_token'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/parser-2.3.0.4/lib/parser/base.rb:162:in `parse'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/parser-2.3.0.4/lib/parser/base.rb:180:in `parse_with_comments'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/parser-2.3.0.4/lib/parser/base.rb:201:in `tokenize'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/processed_source.rb:97:in `parse'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/processed_source.rb:36:in `initialize'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/processed_source.rb:18:in `new'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/processed_source.rb:18:in `from_file'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:270:in `get_processed_source'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:86:in `process_file'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:59:in `block in inspect_files'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:57:in `each'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:57:in `inspect_files'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:35:in `run'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/lib/rubocop/cli.rb:30:in `run'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/bin/rubocop:14:in `block in <top (required)>'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/krororo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rubocop-0.37.2/bin/rubocop:13:in `<top (required)>'
/home/krororo/.rbenv/versions/2.1.7/bin/rubocop:23:in `load'
/home/krororo/.rbenv/versions/2.1.7/bin/rubocop:23:in `<main>'
~~~

~~~
$ rubocop -V
0.37.2 (using Parser 2.3.0.4, running on ruby 2.1.7 x86_64-linux)
~~~

**Comment by bbatsov** [comment]
This is a bug in Parser. //cc @whitequark.

**Comment by whitequark** [comment]
`2.3.0.5`

**Comment by bbatsov** [comment]
10x
