### ISSUE TITLE
"empty range in char class" in Style/ConditionalAssignment

### ISSUE THREAD

**Issue by jeffreyc** [bbatsov/rubocop#2887]
I've run into a pattern that triggers an "An error occurred while Style/ConditionalAssignment cop was inspecting ~/Projects/foo/foo.rb." message.

The following code will trigger the error:
```
if condition
  hash['a-B'] = 'a'
else
  hash['a-B'] = 'b'
end
```

The problem appears to be the `[a-B]` pattern. https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/conditional_assignment.rb#L255 attempts to create a regexp with an invalid pattern (`/hash['a-B']/`), which results in an "empty range in char class" exception. It looks like the solution is to escape the square brackets in `assignment` prior to creating the pattern, though I've only looked at that line, and not the rest of the cop.

Version:
```
% rubocop -V
0.37.2 (using Parser 2.3.0.6, running on ruby 2.2.4 x86_64-darwin15)
```

I verified that the problem still exists with master revision 515a6b42922d8f809df1f38dd210259fddff679f.

Debug output:
```
% rubocop foo.rb -d
For ~/Projects/foo: configuration from ~/Projects/foo/.rubocop.yml
Inheriting configuration from ~/Projects/foo/.rubocop_todo.yml
Default configuration from ~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/config/default.yml
Inheriting configuration from ~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/config/enabled.yml
Inheriting configuration from ~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/config/disabled.yml
configuration from ~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-rspec-1.2.1/config/default.yml
Inspecting 1 file
Scanning ~/Projects/foo/foo.rb
An error occurred while Style/ConditionalAssignment cop was inspecting ~/Projects/foo/foo.rb.
empty range in char class: /hash['a-B']\s*=\s*/
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/style/conditional_assignment.rb:255:in `correction_exceeds_line_limit?'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/style/conditional_assignment.rb:240:in `check_node'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/style/conditional_assignment.rb:182:in `on_if'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/commissioner.rb:42:in `block (2 levels) in on_if'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/commissioner.rb:97:in `with_cop_error_handling'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/commissioner.rb:41:in `block in on_if'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/commissioner.rb:40:in `each'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/commissioner.rb:40:in `on_if'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/ast_node/traversal.rb:96:in `on_def'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/commissioner.rb:46:in `on_def'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/ast_node/traversal.rb:13:in `walk'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/commissioner.rb:59:in `investigate'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cop/team.rb:65:in `inspect_file'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:194:in `inspect_file'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:164:in `block in do_inspection_loop'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:158:in `loop'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:158:in `do_inspection_loop'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:87:in `process_file'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:59:in `block in inspect_files'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:57:in `each'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:57:in `inspect_files'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:35:in `run'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cli.rb:30:in `run'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/bin/rubocop:14:in `block in <top (required)>'
~/.rbenv/versions/2.2.4/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
~/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/bin/rubocop:13:in `<top (required)>'
~/.rbenv/versions/2.2.4/bin/rubocop:23:in `load'
~/.rbenv/versions/2.2.4/bin/rubocop:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Style/ConditionalAssignment cop was inspecting ~/Projects/foo/foo.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.37.2 (using Parser 2.3.0.6, running on ruby 2.2.4 x86_64-darwin15)
Finished in 0.15982622298179194 seconds
% 
```

**Comment by segiddins** [comment]
I believe this may already be fixed on `master`?

**Comment by jeffreyc** [comment]
> I believe this may already be fixed on master?

Sorry, you are correct. My Gemfile.lock claimed I had master installed, but I'm guessing I did not. #2876 should have fixed this. Closing.
