### ISSUE TITLE
Possible bug with `require` in rubocop.yml

### ISSUE THREAD

**Issue by QuotableWater7** [bbatsov/rubocop#2970]
When running `bundle exec rubocop -D`, I now receive the following error:
```
$ bundle exec rubocop
/Users/bloop/.rvm/gems/ruby-2.2.4/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:40:in `require': cannot load such file -- /Users/bloop/Documents/synchroform/rubocop-rspec (LoadError)
	from /Users/bloop/.rvm/gems/ruby-2.2.4/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:40:in `block in load_file'
	from /Users/bloop/.rvm/gems/ruby-2.2.4/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:39:in `each'
	from /Users/bloop/.rvm/gems/ruby-2.2.4/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:39:in `load_file'
	from /Users/bloop/.rvm/gems/ruby-2.2.4/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:99:in `configuration_from_file'
...
```
If I remove `require: rubocop-rspec` from `rubocop.yml` and instead require the gem via the command line, I no longer see the error.

rubocop 0.38.0
rubocop-rspec 1.4.0

Include the output of `rubocop -V`:
```
0.38.0 (using Parser 2.3.0.6, running on ruby 2.2.4 x86_64-darwin14)
```

**Comment by ptarjan** [comment]
Fixed in https://github.com/bbatsov/rubocop/pull/2936

**Comment by QuotableWater7** [comment]
thanks @ptarjan!
