### ISSUE TITLE
Error undefined method `source' for nil:NilClass

### ISSUE THREAD

**Issue by PizzaPill** [bbatsov/rubocop#3039]
I'm getting a ```undefined method 'source' for nil:NilClass``` error when I use rubocop with the ```--auto-correct``` argument. The cops Performance/StartWith and Performance/EndWith seem to be affected. If I run rubocop without them it works, i.e.```rubocop -D --except Performance/StartWith,Performance/EndWith --auto-correct```. It happens at least with rubocop v. 0.39.0.

The offending line for Performance/EndWith looks like this:
```expect(subject.spin).to match(/\n\n\n\n\z/)```

The offending line for Performance/StartWith looks like this:
```expect(unspun).to match(/\AParagraph/)```

output:
```
[snip]
165 files inspected, 178 offenses detected
undefined method `source' for nil:NilClass
[redacted]/gems/rubocop-0.39.0/lib/rubocop/cop/performance/start_with.rb:49:in `block (2 levels) in autocorrect'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/cop/corrector.rb:57:in `block (2 levels) in rewrite'
[redacted]/gems/parser-2.3.0.7/lib/parser/source/rewriter.rb:194:in `transaction'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/cop/corrector.rb:56:in `block in rewrite'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/cop/corrector.rb:54:in `each'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/cop/corrector.rb:54:in `rewrite'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/cop/team.rb:132:in `autocorrect_all_cops'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/cop/team.rb:105:in `autocorrect'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/cop/team.rb:60:in `inspect_file'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/runner.rb:203:in `inspect_file'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/runner.rb:173:in `block in do_inspection_loop'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/runner.rb:163:in `loop'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/runner.rb:163:in `do_inspection_loop'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/runner.rb:87:in `process_file'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/runner.rb:57:in `each'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/runner.rb:57:in `inspect_files'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/runner.rb:35:in `run'
[redacted]/gems/rubocop-0.39.0/lib/rubocop/cli.rb:30:in `run'
[redacted]/gems/rubocop-0.39.0/bin/rubocop:14:in `block in <top (required)>'
[redacted]/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
[redacted]/gems/rubocop-0.39.0/bin/rubocop:13:in `<top (required)>'
[redacted]/bin/rubocop:23:in `load'
[redacted]/bin/rubocop:23:in `<main>'
[redacted]/bin/ruby_executable_hooks:15:in `eval'
[redacted]/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by PizzaPill** [comment]
Thanks for your good work!

2016-04-22 20:00 GMT+02:00 Bozhidar Batsov <notifications@github.com>:
