### ISSUE TITLE
InfiniteCorrectionLoop when auto-correcting constant assignment with implicit array

### ISSUE THREAD

**Issue by grosser** [bbatsov/rubocop#3170]
## code

```
XXX = YYY, ZZZ
```

## result

```
XXX = YYY, ZZZ.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze.freeze ....
```

## expected result

either do not correct or wrap in array and then add freeze

## backtrace

```
vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:169:in `block in do_inspection_loop'
vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:165:in `loop'
vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:165:in `do_inspection_loop'
vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:87:in `process_file'
```

## version
0.40.0 (using Parser 2.3.1.0, running on ruby 2.1.8 x86_64-darwin14.0)

**Comment by alexdowad** [comment]
...Just passed through and discovered that **122** open issues have accumulated! Youch!

**Comment by grosser** [comment]
just close 23 and we are back under 100 ;)
