### ISSUE TITLE
rubocop doesn't run 

### ISSUE THREAD

**Issue by AndreiMotinga** [bbatsov/rubocop#3216]
I can't run it.   Here 
```
➜  ezworks-online git:(master) ✗ gem install rubocop
Fetching: rubocop-0.40.0.gem (100%)
Successfully installed rubocop-0.40.0
1 gem installed
➜  ezworks-online git:(master) ✗ rubocop
/Users/andrei/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fd989cb07e4 rubocop-0.40.0> (NoMethodError)
        from /Users/andrei/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /Users/andrei/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /Users/andrei/.rvm/gems/ruby-2.3.0/gems/rubocop-0.40.0/bin/rubocop:7:in `<top (required)>'
        from /Users/andrei/.rvm/gems/ruby-2.3.0/bin/rubocop:23:in `load'
        from /Users/andrei/.rvm/gems/ruby-2.3.0/bin/rubocop:23:in `<main>'
        from /Users/andrei/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/andrei/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jonas054** [comment]
What about other gems and other versions of rubocop? Do they work? How about other ruby versions?

**Comment by jonas054** [comment]
[This issue](https://github.com/thoughtbot/bitters/issues/215) deals with the same problem and says that the solution is to re-install ruby.

**Comment by AndreiMotinga** [comment]
@jonas054, my apologies for slow response.  
I've updated rubygems and reinstalled ruby as link suggested. It works now, 
Thank you for your help.
