### ISSUE TITLE
`cleanup` isn't concurrent-safe

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#3242]
## Expected behavior

I can run many `rubocop` processes at the same time and they all finish.
## Actual behavior

If two `rubocop` processes finish running at the same time, one of them can clean up the cache directory, and the other throws with:

```
No such file or directory @ rb_file_s_mtime - /cache/rubocop_cache/99c3ac6602c51029823c15c9106045a23955950d/rubocop_cache/02639da205e170093bd901c9c3d16645/_/00ab6b745135000518d35d28f2606f01
21:15:35 /src/vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/result_cache.rb:35:in `mtime'
21:15:35 /src/vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/result_cache.rb:35:in `block in cleanup'
21:15:35 /src/vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/result_cache.rb:35:in `each'
21:15:35 /src/vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/result_cache.rb:35:in `sort_by'
21:15:35 /src/vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/result_cache.rb:35:in `cleanup'
21:15:35 /src/vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:67:in `inspect_files'
21:15:35 /src/vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:35:in `run'
21:15:35 /src/vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/lib/rubocop/cli.rb:30:in `run'
21:15:35 /src/vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/bin/rubocop:14:in `block in <top (required)>'
21:15:35 /usr/lib/rbenv/versions/2.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
21:15:35 /src/vendor/bundle/ruby/2.1.0/gems/rubocop-0.40.0/bin/rubocop:13:in `<top (required)>'
21:15:35 /src/vendor/bundle/ruby/2.1.0/bin/rubocop:23:in `load'
21:15:35 /src/vendor/bundle/ruby/2.1.0/bin/rubocop:23:in `<main>'
```
## Steps to reproduce the problem

```
$ touch /tmp/a.rb
$ for i in `seq 200`; do rubocop /tmp/a.rb & done
```

One of them should error out int result_cache.rb:35.
## RuboCop version

```
$ rubocop -V
0.40.0 (using Parser 2.3.1.0, running on ruby 2.1.2 x86_64-darwin15.0)
```

**Comment by bbatsov** [comment]
Guess we can write some marker file or something to prevent this from happening. Other ideas are welcome as well.

**Comment by jonas054** [comment]
Another way would be to ignore `Errno::ENOENT` exceptions we get on the lines
```ruby
        sorted = files.sort_by { |path| File.mtime(path) }
        remove_files(sorted, dirs, remove_count, verbose)
```
We know the files were there an instant ago, so they were most likely removed by another `rubocop` process, which is something we can accept.
