### ISSUE TITLE
Lint/ShadowedException results in "undefined method `loc' for nil:NilClass" error.

### ISSUE THREAD

**Issue by ashercodeorg** [bbatsov/rubocop#3532]
--------

## Expected behavior

RuboCop reports violations of Lint/ShadowedException, if any.

## Actual behavior

```
$ bundle exec rubocop bin/cron/deliver_poste_messages -d
For /Users/asher/code-dot-org: configuration from /Users/asher/code-dot-org/.rubocop.yml
Inheriting configuration from /Users/asher/code-dot-org/.rubocop_hound.yml
Default configuration from /Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/config/default.yml
Inheriting configuration from /Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/config/enabled.yml
Inheriting configuration from /Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/config/disabled.yml
Inheriting configuration from /Users/asher/code-dot-org/.rubocop_todo.yml
Inspecting 1 file
Scanning /Users/asher/code-dot-org/bin/cron/deliver_poste_messages
An error occurred while Lint/ShadowedException cop was inspecting /Users/asher/code-dot-org/bin/cron/deliver_poste_messages.
undefined method `loc' for nil:NilClass
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/lint/shadowed_exception.rb:59:in `offense_range'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/lint/shadowed_exception.rb:48:in `on_rescue'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:42:in `block (2 levels) in on_rescue'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:97:in `with_cop_error_handling'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:41:in `block in on_rescue'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:40:in `each'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:40:in `on_rescue'
(eval):2:in `block in on_kwbegin'
(eval):2:in `each'
(eval):2:in `on_kwbegin'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_kwbegin'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_begin'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_until'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_begin'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/ast_node/traversal.rb:155:in `on_block'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_block'
(eval):3:in `on_lvasgn'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_lvasgn'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_begin'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/ast_node/traversal.rb:96:in `on_def'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_def'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_begin'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/ast_node/traversal.rb:13:in `walk'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:59:in `investigate'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/team.rb:121:in `investigate'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/team.rb:109:in `offenses'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/team.rb:52:in `inspect_file'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:223:in `inspect_file'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:193:in `block in do_inspection_loop'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:183:in `loop'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:183:in `do_inspection_loop'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:93:in `block in file_offenses'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:103:in `file_offense_cache'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:91:in `file_offenses'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:82:in `process_file'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:57:in `each'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:35:in `run'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cli.rb:72:in `execute_runner'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cli.rb:28:in `run'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/bin/rubocop:14:in `block in <top (required)>'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/bin/rubocop:13:in `<top (required)>'
/Users/asher/.rbenv/versions/2.2.3/bin/rubocop:23:in `load'
/Users/asher/.rbenv/versions/2.2.3/bin/rubocop:23:in `<top (required)>'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/asher/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/Users/asher/.rbenv/versions/2.2.3/bin/bundle:23:in `load'
/Users/asher/.rbenv/versions/2.2.3/bin/bundle:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Lint/ShadowedException cop was inspecting /Users/asher/code-dot-org/bin/cron/deliver_poste_messages.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.42.0 (using Parser 2.3.1.2, running on ruby 2.2.3 x86_64-darwin12.0)
```

## Steps to reproduce the problem

Execute `bundle exec rubocop bin/cron/deliver_poste_messages -d`, where `bin/cron/deliver_poste_messages` is the file https://github.com/code-dot-org/code-dot-org/blob/ea5ee2cecca58c59fc0f609fc78cf63d523059c5/bin/cron/deliver_poste_messages.

## RuboCop version

```
$ rubocop -V
0.32.1 (using Parser 2.2.2.6, running on ruby 2.1.6 x86_64-darwin12.0)
```

**Comment by rrosenblum** [comment]
@ashercodeorg, thanks for the bug report. It appears that this has already been fixed. I was able to reproduce the issue using `0.42.0`. This issue did not happen in `0.43.0` which was created on September 19.
