### ISSUE TITLE
Unable to set RuboCop options for rake task

### ISSUE THREAD

**Issue by spacepants** [bbatsov/rubocop#3539]
Hey there, so I'm running into a super weird issue that I can't quite pin down.

Running rubocop as a rake task is failing to set the options provided in the Rakefile. I've tried with both `0.33.0` and `0.43.0` and both exhibit similar behavior.

--------

## Expected behavior

RuboCop should serve the coding trust, protect the style, uphold the syntax.

## Actual behavior

RuboCop errors out.

`0.33.0`
```
$ bundle exec rake rubocop
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
Running RuboCop...
invalid option: -E
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/options.rb:17:in `parse'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/cli.rb:21:in `run'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/rake_task.rb:50:in `run_cli'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/rake_task.rb:38:in `run_main_task'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/rake_task.rb:30:in `block (2 levels) in initialize'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/file_utils_ext.rb:58:in `verbose'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/rake_task.rb:26:in `block in initialize'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/opt/rubies/2.1.8/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.8/bin/rake:23:in `load'
/opt/boxen/rbenv/versions/2.1.8/bin/rake:23:in `<main>'
RuboCop failed!
```

`0.43.0`
```
$bundle exec rake rubocop
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
Running RuboCop...
wrong number of arguments (5 for 1..3)
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/puppet-3.8.7/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:162:in `safe_load'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/config_loader.rb:161:in `yaml_safe_load'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/config_loader.rb:144:in `load_yaml_configuration'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/config_loader.rb:35:in `load_file'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/config_loader.rb:97:in `configuration_from_file'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/config_store.rb:41:in `for'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/cli.rb:93:in `apply_default_formatter'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/cli.rb:26:in `run'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/rake_task.rb:49:in `run_cli'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/rake_task.rb:37:in `run_main_task'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/rake_task.rb:29:in `block (2 levels) in initialize'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/file_utils_ext.rb:58:in `verbose'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/rake_task.rb:27:in `block in initialize'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/opt/rubies/2.1.8/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.8/bin/rake:23:in `load'
/opt/boxen/rbenv/versions/2.1.8/bin/rake:23:in `<main>'
RuboCop failed!
```
## Steps to reproduce the problem

When it's not invoked as a rake task, rubocop works fine.
`0.33.0`
```
$ bundle exec rubocop -d
For /Users/paulba/welp/puppet-module-skeleton/module: configuration from /Users/paulba/welp/puppet-module-skeleton/module/.rubocop.yml
Default configuration from /opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/config/default.yml
Inheriting configuration from /opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/config/enabled.yml
Inheriting configuration from /opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/config/disabled.yml
Inspecting 8 files
Scanning /Users/paulba/welp/puppet-module-skeleton/module/Gemfile
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/Guardfile
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/Rakefile
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/acceptance/class_spec.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/classes/coverage_spec.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/classes/example_spec.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/spec_helper.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/spec_helper_acceptance.rb
.

8 files inspected, no offenses detected
Finished in 0.126386 seconds
```

`0.43.0`
```
bundle exec rubocop -d
For /Users/paulba/welp/puppet-module-skeleton/module: configuration from /Users/paulba/welp/puppet-module-skeleton/module/.rubocop.yml
/Users/paulba/welp/puppet-module-skeleton/module/.rubocop.yml: Lint/SpaceBeforeFirstArg has the wrong namespace - should be Style
Default configuration from /opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/config/default.yml
Inheriting configuration from /opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/config/enabled.yml
Inheriting configuration from /opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/config/disabled.yml
Inspecting 8 files
Scanning /Users/paulba/welp/puppet-module-skeleton/module/Gemfile
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/Guardfile
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/Rakefile
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/acceptance/class_spec.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/classes/coverage_spec.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/classes/example_spec.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/spec_helper.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/spec_helper_acceptance.rb
.

8 files inspected, no offenses detected
Finished in 0.10242 seconds
```

What's really puzzling is that if I invoke rubocop through a custom task, it works fine in `0.33.0`.
```
$ bundle exec rake rubocop_debug
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
Running RuboCop...
For /Users/paulba/welp/puppet-module-skeleton/module: configuration from /Users/paulba/welp/puppet-module-skeleton/module/.rubocop.yml
Default configuration from /opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/config/default.yml
Inheriting configuration from /opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/config/enabled.yml
Inheriting configuration from /opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/config/disabled.yml
Inspecting 8 files
Scanning /Users/paulba/welp/puppet-module-skeleton/module/Gemfile
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/Guardfile
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/Rakefile
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/acceptance/class_spec.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/classes/coverage_spec.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/classes/example_spec.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/spec_helper.rb
.Scanning /Users/paulba/welp/puppet-module-skeleton/module/spec/spec_helper_acceptance.rb
.

8 files inspected, no offenses detected
```

Still errors out in `0.43.0` though:
```
$ bundle exec rake rubocop_debug
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
Running RuboCop...
For /Users/paulba/welp/puppet-module-skeleton/module: wrong number of arguments (5 for 1..3)
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/puppet-3.8.7/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:162:in `safe_load'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/config_loader.rb:161:in `yaml_safe_load'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/config_loader.rb:144:in `load_yaml_configuration'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/config_loader.rb:35:in `load_file'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/config_loader.rb:97:in `configuration_from_file'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/config_store.rb:41:in `for'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/cli.rb:93:in `apply_default_formatter'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/cli.rb:26:in `run'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/rake_task.rb:49:in `run_cli'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/rake_task.rb:37:in `run_main_task'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/rake_task.rb:29:in `block (2 levels) in initialize'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/file_utils_ext.rb:58:in `verbose'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rubocop-0.43.0/lib/rubocop/rake_task.rb:27:in `block in initialize'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/opt/rubies/2.1.8/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/opt/rubies/2.1.8/lib/ruby/gems/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.8/bin/rake:23:in `load'
/opt/boxen/rbenv/versions/2.1.8/bin/rake:23:in `<main>'
RuboCop failed!
```

## RuboCop version

Include the output of `rubocop -V`.

`0.33.0`
```
$ bundle exec rubocop -V
0.33.0 (using Parser 2.3.1.4, running on ruby 2.1.8 x86_64-darwin14.0)
```

`0.43.0`
```
$ bundle exec rubocop -V
0.43.0 (using Parser 2.3.1.4, running on ruby 2.1.8 x86_64-darwin14.0)
```

## Environment info

Here's my setup:
```
$ bundle exec rake -V
rake, version 11.3.0
$ bundle exec rubocop -V
0.33.0 (using Parser 2.3.1.4, running on ruby 2.1.8 x86_64-darwin14.0)
```

Gemfile (Same Gemfile for both, but I'm unpinning the RuboCop version.)
```
source ENV['GEM_SOURCE'] || "https://rubygems.org"

group :test do
  gem "rake"
  gem "puppet", ENV['PUPPET_GEM_VERSION'] || '~> 3.8.0'
  gem "rspec", '< 3.2.0'
  gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git'
  gem "puppetlabs_spec_helper"
  gem "metadata-json-lint"
  gem "rspec-puppet-facts"
  gem 'rubocop', '0.33.0'
  gem 'simplecov', '>= 0.11.0'
  gem 'simplecov-console'

  gem "puppet-lint-absolute_classname-check"
  gem "puppet-lint-leading_zero-check"
  gem "puppet-lint-trailing_comma-check"
  gem "puppet-lint-version_comparison-check"
  gem "puppet-lint-classes_and_types_beginning_with_digits-check"
  gem "puppet-lint-unquoted_string-check"
  gem 'puppet-lint-resource_reference_syntax'
end

group :development do
  gem "travis"
  gem "travis-lint"
  gem "puppet-blacksmith"
  gem "guard-rake"
end

group :system_tests do
  gem "beaker"
  gem "beaker-rspec"
  gem "beaker-puppet_install_helper"
end
```

Rakefile
```
require 'rubygems'
require 'bundler/setup'

require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet/version'
require 'puppet/vendor/semantic/lib/semantic' unless Puppet.version.to_f < 3.6
require 'puppet-lint/tasks/puppet-lint'
require 'puppet-syntax/tasks/puppet-syntax'
require 'metadata-json-lint/rake_task'
require 'rubocop/rake_task'

# These gems aren't always present, for instance
# on Travis with --without development
begin
  require 'puppet_blacksmith/rake_tasks'
rescue LoadError # rubocop:disable Lint/HandleExceptions
end

RuboCop::RakeTask.new(:rubocop) do |task|
  task.options = %w(-d)
end

RuboCop::RakeTask.new(:rubocop_debug) do |task|
  task.options = %w(-d)
end

exclude_paths = [
  "bundle/**/*",
  "pkg/**/*",
  "vendor/**/*",
  "spec/**/*"
]

Rake::Task[:lint].clear

PuppetLint.configuration.relative = true
PuppetLint.configuration.disable_80chars
PuppetLint.configuration.disable_class_inherits_from_params_class
PuppetLint.configuration.disable_class_parameter_defaults
PuppetLint.configuration.fail_on_warnings = true

PuppetLint::RakeTask.new :lint do |config|
  config.ignore_paths = exclude_paths
end

PuppetSyntax.exclude_paths = exclude_paths

desc "Run acceptance tests"
RSpec::Core::RakeTask.new(:acceptance) do |t|
  t.pattern = 'spec/acceptance'
end

desc "Populate CONTRIBUTORS file"
task :contributors do
  system("git log --format='%aN' | sort -u > CONTRIBUTORS")
end

desc "Run syntax, lint, and spec tests."
task :test => [
  :metadata_lint,
  :syntax,
  :lint,
  :rubocop,
  :spec
]
```

Any ideas? Thanks!

**Comment by bquorning** [comment]
When you run `rubocop` from the command line, it runs in isolation. Which just works.

When you run `rubocop` via Rake, whatever else is loaded by the Rakefile may influence the environment that RuboCop will be executed in. And it seems that your Rakefile loads Puppet which somehow loads https://github.com/puppetlabs/puppet/blob/3.8.7/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb which, [on line 162](https://github.com/puppetlabs/puppet/blob/3.8.7/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb#L162) patches `YAML#safe_load`. The monkey patch defines the method with an arity of 3, while RubyCop expects it to have an arity of 5.

**Comment by spacepants** [comment]
Ah, okay. Thanks so much for the help.
