### ISSUE TITLE
Version 0.44.0 does not work for me

### ISSUE THREAD

**Issue by Bjoernsen** [bbatsov/rubocop#3608]
Yesterday, rubocop worked great, But with 0.44 it doesn't.

Version 0.43
```shell
$ gem install rubocop --no-ri --no-rdoc
Successfully installed rainbow-2.1.0
Successfully installed ast-2.3.0
Successfully installed parser-2.3.1.4
Successfully installed powerpack-0.1.1
Successfully installed ruby-progressbar-1.8.1
Successfully installed unicode-display_width-1.1.1
Successfully installed rubocop-0.43.0
7 gems installed
$ rubocop
Inspecting 538 files
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

538 files inspected, no offenses detected
Build succeeded
```

Version 0.44
```shell
$ gem install rubocop --no-ri --no-rdoc
Successfully installed rainbow-2.1.0
Successfully installed ast-2.3.0
Successfully installed parser-2.3.1.4
Successfully installed powerpack-0.1.1
Successfully installed ruby-progressbar-1.8.1
Successfully installed unicode-display_width-1.1.1
Successfully installed rubocop-0.44.0
7 gems installed
$ rubocop
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/rubocop-0.44.0/lib/rubocop/cop/performance/case_when_splat.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/rubocop-0.44.0/lib/rubocop.rb:161:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/rubocop-0.44.0/bin/rubocop:6:in `<top (required)>'
	from /usr/local/bundle/bin/rubocop:22:in `load'
	from /usr/local/bundle/bin/rubocop:22:in `<main>'
ERROR: Build failed: exit code 1
```

**Comment by Bjoernsen** [comment]
With `rubocop-0.44.1` there is no error anymore. Thanks!
