### ISSUE TITLE
Style/RedundantReturn check raises error when if/until block is empty

### ISSUE THREAD

**Issue by buren** [bbatsov/rubocop#3635]
`Style/RedundantReturn` check raises error when `if/until` block is empty.

--------

## Expected behavior

No error.

## Actual behavior

Rubocop prints the error:

```
1 error occurred:
An error occurred while Style/RedundantReturn cop was inspecting <filename>.rb
```

## Steps to reproduce the problem

With `Style/RedundantReturn` enabled.

With code

```ruby
# foo.rb
def foo
  if bar
  end
end
```

Run `rubocop foo.rb`

## RuboCop version

```
0.44.1 (using Parser 2.3.1.4, running on ruby 2.3.1 x86_64-darwin15)
```

## Debug output

The last few lines of the stack trace:

```
undefined method `type' for nil:NilClass
/Users/buren/.gem/ruby/2.3.1/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:79:in `check_branch'
/Users/buren/.gem/ruby/2.3.1/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:109:in `check_if_node'
/Users/buren/.gem/ruby/2.3.1/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:82:in `check_branch'
/Users/buren/.gem/ruby/2.3.1/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:75:in `on_method_def'
/Users/buren/.gem/ruby/2.3.1/gems/rubocop-0.44.1/lib/rubocop/cop/mixin/on_method_def.rb:9:in `on_def'
```

**Comment by tiagocasanovapt** [comment]
I was also looking for this but it seems there's already a PR for it #3607

**Comment by buren** [comment]
@tiagocasanovapt you're absolutely right 👍 Closing this, since #3607 fixed it.
