### ISSUE TITLE
can anyone help me please to solve this issue.?

### ISSUE THREAD

**Issue by zravo1** [bbatsov/rubocop#3790]
Please help me to solve this issue.
i'm trying to recompile an app. i've done all necessary changes, but when i try to recompile it. It gives me those errors; please check them and help to resolve the issue. thank you.

..\3-Out\nameoftheapp.apk\smali\myname\nameoftheapp\AboutUs.smali[43,21] Error for input '"This App is designed by myname. For any suggestions and queries please e-mail us at: \myemail@gmail.com 

Disclaimer : All the contents present in this app are collected from internet. 

Author : myname(start with letter k)"': Invalid escape sequence \k
..\3-Out\nameoftheapp.apk\smali\myname\nameoftheapp\AboutUs.smali[45,4] missing STRING_LITERAL at 'invoke-virtual'
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: myname/nameoftheapp/AboutUs.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:71)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:55)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:385)
	at brut.androlib.Androlib.buildSources(Androlib.java:312)
	at brut.androlib.Androlib.build(Androlib.java:295)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)

i've hide my packagename and name of the app just for security. Please help me.

**Comment by dgollahon** [comment]
@zravo1: Are you sure this is the repository you meant to open this issue on? Rubocop is a code style checking tool for ruby programs, and does not seem to be related to the trouble you are having with your app.
