### ISSUE TITLE
ErrorOccured, undefined method `+' for :Na:Symbol, when bundle exec

### ISSUE THREAD

**Issue by jabropt** [bbatsov/rubocop#3806]
## Steps to reproduce the problem
error  occured only when `bundle exec` is attached.

'bundle exec rubocop -a hogehgoe.rb -d

```
undefined method `+' for :Na:Symbol
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/style/first_parameter_indentation.rb:36:in `on_send'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:41:in `block (2 levels) in on_send'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:96:in `with_cop_error_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:40:in `block in on_send'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:39:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:39:in `on_send'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:101:in `block in on_send'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:99:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:99:in `each_with_index'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:99:in `on_send'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:45:in `on_send'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:101:in `block in on_send'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:99:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:99:in `each_with_index'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:99:in `on_send'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:45:in `on_send'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:154:in `on_block'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:45:in `on_block'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:154:in `on_block'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:45:in `on_block'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:95:in `on_def'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:45:in `on_def'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:45:in `on_begin'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:88:in `on_class'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:45:in `on_class'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:12:in `walk'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:58:in `investigate'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/team.rb:120:in `investigate'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/team.rb:100:in `offenses'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/team.rb:51:in `inspect_file'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:243:in `inspect_file'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:190:in `block in do_inspection_loop'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:222:in `block in iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:215:in `loop'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:215:in `iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:186:in `do_inspection_loop'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:101:in `block in file_offenses'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:111:in `file_offense_cache'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:99:in `file_offenses'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:90:in `process_file'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:65:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:65:in `reduce'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:65:in `each_inspected_file'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:57:in `inspect_files'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:36:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cli.rb:72:in `execute_runner'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cli.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/bin/rubocop:13:in `block in <top (required)>'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/bin/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
./bin/bundle:3:in `load'
./bin/bundle:3:in `<main>'
```
## RuboCop version
```
$ rubocop -V
0.46.0 (using Parser 2.3.3.1, running on ruby 2.3.1 x86_64-darwin15)
```

**Comment by bbatsov** [comment]
What are the contents of this file?

**Comment by jabropt** [comment]
```
class A
  private

  def hoge
  end
end
```

```
For /Users/jabropt/sample: configuration from /Users/jabropt/sample/.rubocop.yml
Default configuration from /usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/config/default.yml
Inheriting configuration from /usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/config/enabled.yml
Inheriting configuration from /usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/config/disabled.yml
Inspecting 1 file
Scanning /Users/jabropt/sample/app/controllers/sample_controller.rb
An error occurred while Style/IndentationConsistency cop was inspecting /Users/jabropt/sample/app/controllers/sample_controller.rb.
  undefined method `-' for :Na:Symbol
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/mixin/autocorrect_alignment.rb:77:in `block in each_bad_alignment'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/mixin/autocorrect_alignment.rb:74:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/mixin/autocorrect_alignment.rb:74:in `each_bad_alignment'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/mixin/autocorrect_alignment.rb:34:in `check_alignment'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/style/indentation_consistency.rb:46:in `block in check'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/style/indentation_consistency.rb:46:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/style/indentation_consistency.rb:46:in `check'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/style/indentation_consistency.rb:24:in `on_begin'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:41:in `block (2 levels) in on_begin'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:96:in `with_cop_error_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:40:in `block in on_begin'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:39:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:39:in `on_begin'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:88:in `on_class'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:45:in `on_class'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/ast_node/traversal.rb:12:in `walk'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/commissioner.rb:58:in `investigate'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/team.rb:120:in `investigate'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/team.rb:100:in `offenses'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cop/team.rb:51:in `inspect_file'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:243:in `inspect_file'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:190:in `block in do_inspection_loop'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:222:in `block in iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:215:in `loop'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:215:in `iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:186:in `do_inspection_loop'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:101:in `block in file_offenses'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:111:in `file_offense_cache'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:99:in `file_offenses'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:90:in `process_file'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:65:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:65:in `reduce'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:65:in `each_inspected_file'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:57:in `inspect_files'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/runner.rb:36:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cli.rb:72:in `execute_runner'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cli.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/bin/rubocop:13:in `block in <top (required)>'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/bin/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
                                                                                                                                                                                     ./bin/bundle:3:in `load'
./bin/bundle:3:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Style/IndentationConsistency cop was inspecting /Users/jabropt/sample/app/controllers/sample_controller.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
  Mention the following information in the issue report:
                                                   0.46.0 (using Parser 2.3.3.1, running on ruby 2.3.1 x86_64-darwin15)
Finished in 0.19710620798286982 seconds
```

**Comment by jabropt** [comment]
This solved.
I use unicode-display_width (0.1.1).
after update to unicode-display_width (1.1.2), no error occured.
