### ISSUE TITLE
rubocop run fails - Could not find 'rainbow'

### ISSUE THREAD

**Issue by juushya** [bbatsov/rubocop#4166]
## Expected behavior

Default expected behavior is to get a syntax check log.

## Actual behavior

rubocop does not run and fails with error.

## Steps to reproduce the problem

rubocop

## RuboCop version

Include the output of `rubocop -V`.

```
$ rubocop -V
/usr/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'rainbow' (< 3.0, >= 1.99.1) among 90 total gem(s) (Gem::LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:1295:in `block in activate_dependencies'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:1284:in `each'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:1284:in `activate_dependencies'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:1266:in `activate'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:54:in `gem'
	from /usr/local/bin/rubocop:22:in `<main>'
```

## Additional information

```
root@box:~/module-test# gem -v
2.6.11
```
```
root@box:~/module-test# bundler -v
Bundler version 1.13.6
```
```
root@box:~/module-test# uname -a
Linux Kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.16-1kali1 (2017-03-24) x86_64 GNU/Linux
```

**Comment by sadovnik** [comment]
It used to work or this is the first run?
Have you tried to reinstall it?

**Comment by juushya** [comment]
@sadovnik Yes it used to work. I think it broke after a dist-upgrade. I have tried installing it again but it fails too.

**Comment by bbatsov** [comment]
I can't reproduce this. Likely it's just a local problem of your setup.
