### ISSUE TITLE
Rails/Blank cop: undefined method `type' for nil:NilClass

### ISSUE THREAD

**Issue by doits** [bbatsov/rubocop#4171]
The following file crashes rubocop with enabled Rails linters:

```
class Something
  def meth
    something || blub
  end
end
```

```
rubocop -R bla.rb
```

```
An error occurred while Rails/Blank cop was inspecting /Users/markus/svn/bla.rb:3:4.
undefined method `type' for nil:NilClass
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/rails/blank.rb:45:in `nil_or_empty?'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/rails/blank.rb:79:in `on_or'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:43:in `block (2 levels) in on_or'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:106:in `with_cop_error_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:42:in `block in on_or'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:41:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:41:in `on_or'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:95:in `on_def'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_def'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:88:in `on_class'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_class'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:12:in `walk'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:124:in `investigate'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:112:in `offenses'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:54:in `inspect_file'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:248:in `inspect_file'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:195:in `block in do_inspection_loop'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:227:in `block in iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:220:in `loop'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:220:in `iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:191:in `do_inspection_loop'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:101:in `block in file_offenses'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:111:in `file_offense_cache'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:99:in `file_offenses'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:90:in `process_file'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `reduce'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `each_inspected_file'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:57:in `inspect_files'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:36:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cli.rb:72:in `execute_runner'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cli.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/bin/rubocop:13:in `block in <top (required)>'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/bin/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:22:in `load'
/usr/local/bin/rubocop:22:in `<main>'
```

--------

## RuboCop version

```
0.48.0 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-darwin16)
```

**Comment by dworld-software** [comment]
@Drenmi Same error occurs on this code after your commits.

```ruby
class Something
  def meth
    something || !blub
  end
end
