### ISSUE TITLE
Errors with Rails/Blank cop

### ISSUE THREAD

**Issue by afdev82** [bbatsov/rubocop#4183]
I have errors with the Rails/Blank cop while running `rubocop` with Rails 4.2.8.

This is the stack trace:
```
undefined method `type' for nil:NilClass
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/rails/blank.rb:45:in `nil_or_empty?'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/rails/blank.rb:79:in `on_or'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:43:in `block (2 levels) in on_or'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:106:in `with_cop_error_handling'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:42:in `block in on_or'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:41:in `each'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:41:in `on_or'
(eval):2:in `block in on_or'
(eval):2:in `each'
(eval):2:in `on_or'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_or'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:154:in `on_block'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_block'
(eval):2:in `block in on_pair'
(eval):2:in `each'
(eval):2:in `on_pair'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_pair'
(eval):2:in `block in on_hash'
(eval):2:in `each'
(eval):2:in `on_hash'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_hash'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:101:in `block in on_send'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:99:in `each'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:99:in `each_with_index'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:99:in `on_send'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_send'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_begin'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:154:in `on_block'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_block'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_begin'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:141:in `on_while'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_module'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:141:in `on_while'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_module'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:12:in `walk'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:124:in `investigate'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:104:in `offenses'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:54:in `inspect_file'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:248:in `inspect_file'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:195:in `block in do_inspection_loop'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:227:in `block in iterate_until_no_changes'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:220:in `loop'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:220:in `iterate_until_no_changes'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:191:in `do_inspection_loop'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:101:in `block in file_offenses'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:111:in `file_offense_cache'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:99:in `file_offenses'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:90:in `process_file'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `each'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `reduce'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `each_inspected_file'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:57:in `inspect_files'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:36:in `run'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cli.rb:72:in `execute_runner'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cli.rb:27:in `run'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/bin/rubocop:13:in `block in <top (required)>'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/bin/rubocop:12:in `<top (required)>'
/home/antonio/.rbenv/versions/2.4.0/bin/rubocop:22:in `load'
/home/antonio/.rbenv/versions/2.4.0/bin/rubocop:22:in `<main>'
```
--------

## RuboCop version
```
$ rubocop -V
0.48.0 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-linux)
```

**Comment by afdev82** [comment]
Duplicate of #4179
