### ISSUE TITLE
Errors with ThreadSafety/InstanceVariableInClassMethod cop

### ISSUE THREAD

**Issue by afdev82** [bbatsov/rubocop#4184]
I have errors with the ThreadSafety/InstanceVariableInClassMethod cop with Rails 4.2.8.

For example, while checking this code it fails on line 5 and 7:
```ruby
def get_ancestors(cat)
  @tree ||= []

  if cat.parent_group.nil?
    return @tree
  else
    @tree << cat.parent_group.name
    get_ancestors(cat.parent_group)
  end
end
```

This is the backtrace:
```
undefined method `command?' for s(:ivar, :@current_alchemy_site):RuboCop::AST::Node
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-thread_safety-0.3.2/lib/rubocop/cop/thread_safety/instance_variable_in_class_method.rb:55:in `block in singleton_method_definition?'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-thread_safety-0.3.2/lib/rubocop/cop/thread_safety/instance_variable_in_class_method.rb:53:in `any?'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-thread_safety-0.3.2/lib/rubocop/cop/thread_safety/instance_variable_in_class_method.rb:53:in `singleton_method_definition?'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-thread_safety-0.3.2/lib/rubocop/cop/thread_safety/instance_variable_in_class_method.rb:33:in `class_method_definition?'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-thread_safety-0.3.2/lib/rubocop/cop/thread_safety/instance_variable_in_class_method.rb:21:in `on_ivar'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:43:in `block (2 levels) in on_ivar'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:106:in `with_cop_error_handling'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:42:in `block in on_ivar'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:41:in `each'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:41:in `on_ivar'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:101:in `block in on_send'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:99:in `each'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:99:in `each_with_index'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:99:in `on_send'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_send'
(eval):2:in `block in on_pair'
(eval):2:in `each'
(eval):2:in `on_pair'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_pair'
(eval):2:in `block in on_hash'
(eval):2:in `each'
(eval):2:in `on_hash'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_hash'
(eval):2:in `block in on_pair'
(eval):2:in `each'
(eval):2:in `on_pair'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_pair'
(eval):2:in `block in on_hash'
(eval):2:in `each'
(eval):2:in `on_hash'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_hash'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:101:in `block in on_send'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:99:in `each'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:99:in `each_with_index'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:99:in `on_send'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_send'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_begin'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:95:in `on_def'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_def'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_begin'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:88:in `on_class'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_class'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:12:in `walk'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:124:in `investigate'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:112:in `offenses'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:54:in `inspect_file'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:248:in `inspect_file'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:195:in `block in do_inspection_loop'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:227:in `block in iterate_until_no_changes'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:220:in `loop'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:220:in `iterate_until_no_changes'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:191:in `do_inspection_loop'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:101:in `block in file_offenses'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:111:in `file_offense_cache'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:99:in `file_offenses'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:90:in `process_file'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `each'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `reduce'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `each_inspected_file'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:57:in `inspect_files'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:36:in `run'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cli.rb:72:in `execute_runner'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cli.rb:27:in `run'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/bin/rubocop:13:in `block in <top (required)>'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/home/antonio/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/bin/rubocop:12:in `<top (required)>'
/home/antonio/.rbenv/versions/2.4.0/bin/rubocop:22:in `load'
/home/antonio/.rbenv/versions/2.4.0/bin/rubocop:22:in `<main>'
```
--------
## RuboCop version

```
$ rubocop -V
0.48.0 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-linux)
```

**Comment by mikegee** [comment]
@afdev82 The latest release of rubocop-thread_safety should resolve this. Please open an issue at https://github.com/covermymeds/rubocop-thread_safety, if you still have trouble. (The problem wasn't in Rubocop itself.)

**Comment by afdev82** [comment]
Thank you, the version 3.3.0 solves the issue.
