### ISSUE TITLE
Rubocop crashes in Rails/Blank cop

### ISSUE THREAD

**Issue by lukaso** [bbatsov/rubocop#4200]
On upgrading to the latest version of rubocop, the Rails/Blank cop fails.

I will try to find a reproducing case, but for now I don't have that.

--------

## Expected behavior

Not to crash

## Actual behavior

```
An error occurred while Rails/Blank cop was inspecting ~/projects/dont_stop_believin_in_mongoid/lib/x_mongoid/mongoid_persistence_adapter.rb:14:23.
undefined method `type' for nil:NilClass
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/rails/blank.rb:45:in `nil_or_empty?'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/rails/blank.rb:79:in `on_or'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:43:in `block (2 levels) in on_or'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:106:in `with_cop_error_handling'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:42:in `block in on_or'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:41:in `each'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:41:in `on_or'
(eval):3:in `on_lvasgn'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_lvasgn'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_begin'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:95:in `on_def'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_def'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_begin'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:88:in `on_class'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_class'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:141:in `on_while'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:47:in `on_module'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/ast/traversal.rb:12:in `walk'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:124:in `investigate'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:112:in `offenses'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cop/team.rb:54:in `inspect_file'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:248:in `inspect_file'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:195:in `block in do_inspection_loop'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:227:in `block in iterate_until_no_changes'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:220:in `loop'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:220:in `iterate_until_no_changes'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:191:in `do_inspection_loop'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:101:in `block in file_offenses'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:111:in `file_offense_cache'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:99:in `file_offenses'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:90:in `process_file'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `each'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `reduce'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:65:in `each_inspected_file'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/runner.rb:36:in `run'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cli.rb:72:in `execute_runner'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/lib/rubocop/cli.rb:27:in `run'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/bin/rubocop:13:in `block in <top (required)>'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.48.0/bin/rubocop:12:in `<top (required)>'
/Users/xxxx/.rbenv/versions/2.4.0/bin/rubocop:22:in `load'
/Users/xxxx/.rbenv/versions/2.4.0/bin/rubocop:22:in `<top (required)>'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/xxxx/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/Users/xxxx/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
/Users/xxxx/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
```

## Steps to reproduce the problem

This happened when upgrading from v0.47 to v0.48.

Beginning of the file that fails:

```
module XMongoid
  class MongoidPersistenceAdapter < X::Persistence::PersistenceAdapter
    def store(x)
      if x.id
        XRecord.find(x.id).update_attributes!(x_serializer.serialize(x).attributes)
      else
        x.id = generate_id
        x_serializer.serialize(x).save!
      end
    end

    def find(x_id, qualifying_attributes = {})
      found_document = find_mongo_document(x_id, qualifying_attributes) ||
                       x_not_existent_error(x_id, qualifying_attributes)

      x_serializer.deserialize(found_document)
    end
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.48.0 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-darwin16)
```

**Comment by bbatsov** [comment]
This is fixed on `master`.
