### ISSUE TITLE
Rails/RelativeDateConstant crashes on dual-assigning constants

### ISSUE THREAD

**Issue by paul** [bbatsov/rubocop#4249]
This is poor code which I'm cleaning up, but this cop errors out when "dual-assigning" two constants. I've generated a simple test case below.

Thanks for all your hard work on rubocop, we really appreciate it!

## Steps to reproduce the problem

```ruby
class MyClass
  CONSTA, CONSTB = 1, 2
end
```

```
$ rubocop --only Rails/RelativeDateConstant rubocop_test.rb -d
For /Users/rando/Code/textus/text-us-web-app: configuration from /Users/rando/Code/textus/text-us-web-app/.rubocop.yml
Default configuration from /Users/rando/.gem/ruby/2.3.0/gems/rubocop-0.48.1/config/default.yml
Inheriting configuration from /Users/rando/.gem/ruby/2.3.0/gems/rubocop-0.48.1/config/enabled.yml
Inheriting configuration from /Users/rando/.gem/ruby/2.3.0/gems/rubocop-0.48.1/config/disabled.yml
Inspecting 1 file
Scanning /Users/rando/Code/textus/text-us-web-app/rubocop_test.rb
An error occurred while Rails/RelativeDateConstant cop was inspecting /Users/rando/Code/textus/text-us-web-app/rubocop_test.rb:3:2.
undefined method `lambda_or_proc?' for nil:NilClass
/Users/rando/.gem/ruby/2.3.0/gems/rubocop-0.48.1/lib/rubocop/cop/rails/relative_date_constant.rb:30:in `on_casgn'
/Users/rando/.gem/ruby/2.3.0/gems/rubocop-0.48.1/lib/rubocop/cop/commissioner.rb:43:in `block (2 levels) in on_casgn'
/Users/rando/.gem/ruby/2.3.0/gems/rubocop-0.48.1/lib/rubocop/cop/commissioner.rb:106:in `with_cop_error_handling'
/Users/rando/.gem/ruby/2.3.0/gems/rubocop-0.48.1/lib/rubocop/cop/commissioner.rb:42:in `block in on_casgn'
/Users/rando/.gem/ruby/2.3.0/gems/rubocop-0.48.1/lib/rubocop/cop/commissioner.rb:41:in `each'
/Users/rando/.gem/ruby/2.3.0/gems/rubocop-0.48.1/lib/rubocop/cop/commissioner.rb:41:in `on_casgn'
...
```

## RuboCop version

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.3.0 x86_64-darwin16)
```

**Comment by bbatsov** [comment]
This is probably fixed on `master`, but in general I have a feeling this cop doesn't handle multiple assignment. We should take a look into this.

**Comment by mikegee** [comment]
> This is probably fixed on `master`

I confirmed no error from the example given here on `master`.

**Comment by paul** [comment]
I just pulled the latest master, and can also confirm that it work. Feel free to close this, and I will await the next release. Thanks!

**Comment by bbatsov** [comment]
Well, this bug is fixed, but I also confirmed the cop doesn't really do anything in the case of multiple assignment to constants, so we need to fix this.
