### ISSUE TITLE
Error in MethodCallWithArgsParentheses auto-correct

### ISSUE THREAD

**Issue by aripollak** [bbatsov/rubocop#4275]
With MethodCallWithArgsParentheses enabled, running `rubocop -a` on this file:

```ruby
def foo
  yield true
end
```

Results in this exception:

```
undefined method `selector' for #<Parser::Source::Map::Keyword:0x0055d603311da0>
/home/ari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.48.1/lib/rubocop/cop/style/method_call_with_args_parentheses.rb:96:in `args_begin'
/home/ari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.48.1/lib/rubocop/cop/style/method_call_with_args_parentheses.rb:69:in `block in autocorrect'
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.3.3 x86_64-linux)
```

**Comment by Drenmi** [comment]
Thanks for the report @aripollak. I can reproduce this issue. Will work in it tonight. 🙂
