### ISSUE TITLE
Crash on Class method else without rescue

### ISSUE THREAD

**Issue by guilhermesimoes** [bbatsov/rubocop#4348]
Just testing some stuff and this crashes the latest Rubocop:

```
class ElseWithoutRescue
  def m
  end
  else
end
```

Stacktrace:
```
undefined method `begin_pos' for nil:NilClass
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/parser-2.4.0.0/lib/parser/source/range.rb:182:in `join'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/parser-2.4.0.0/lib/parser/builders/default.rb:1191:in `join_exprs'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/parser-2.4.0.0/lib/parser/builders/default.rb:1273:in `collection_map'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/parser-2.4.0.0/lib/parser/builders/default.rb:1026:in `begin_body'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/parser-2.4.0.0/lib/parser/ruby21.rb:3366:in `_reduce_9'
.../ruby-2.1.10/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
.../ruby-2.1.10/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/parser-2.4.0.0/lib/parser/base.rb:162:in `parse'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/parser-2.4.0.0/lib/parser/base.rb:209:in `tokenize'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/rubocop-0.48.1/lib/rubocop/processed_source.rb:99:in `tokenize'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/rubocop-0.48.1/lib/rubocop/processed_source.rb:94:in `parse'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/rubocop-0.48.1/lib/rubocop/processed_source.rb:36:in `initialize'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/rubocop-0.48.1/lib/rubocop/processed_source.rb:17:in `new'
.../ruby-2.1.10/lib/ruby/gems/2.1.0/gems/rubocop-0.48.1/lib/rubocop/processed_source.rb:17:in `from_file'
```

|            | Version |
|------------|---------|
| Ruby       | ruby 2.1.10p492   |
| Rubocop | 0.48.1 (and master 4430501)   |

Possibly relevant cop: https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/lint/useless_else_without_rescue.rb

**Comment by Drenmi** [comment]
This is a problem with [Parser](https://github.com/whitequark/parser), so you probably need to open this issue over there. 🙂

**Comment by guilhermesimoes** [comment]
Dang, you are right, and I just found a duplicate (I swear I searched first :disappointed:).

#4344 

Closed.
