### ISSUE TITLE
Use Array.new with a block instead of .times.map.

### ISSUE THREAD

**Issue by tonobo** [bbatsov/rubocop#4658]
## Expected behavior

To not break application by using auto correct.

## Actual behavior

`#<ArgumentError: negative array size>`

## Steps to reproduce the problem

```ruby
  args.negative_size.times.map do
    puts "test"
  end
```

`rubocop -a`

## RuboCop version

```
> rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.3.1 x86_64-linux-gnu)
```

**Comment by pocke** [comment]
This is a problem of `Performance/TimesMap`  cop.


Minimal code to reproduce : 


```ruby
-1.times.map{|x| puts x}
```



```bash
$ ruby test.rb # Do nothing

$ rubocop -a --only Performance/TimesMap
Inspecting 1 file
C

Offenses:

test.rb:1:1: C: [Corrected] Use Array.new with a block instead of .times.map.
-1.times.map{|x| puts x}
^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected

$ cat test.rb
Array.new(-1){|x| puts x}

$ ruby test.rb
test.rb:1:in `initialize': negative array size (ArgumentError)
	from test.rb:1:in `new'
	from test.rb:1:in `<main>'
```
