### ISSUE TITLE
rubocop crash parsing certain files with syntax errors

### ISSUE THREAD

**Issue by nelhage-stripe** [bbatsov/rubocop#4675]
Rubocopping certain files with syntax errors results in a rubocop crash, instead of a nice error message with the syntax error.

The most minimal test case I've been able to produce is:

```ruby
def func
  case true
  when true
    {
      author: true if x.nil?,
    }

    foo
  else
  end
end
```

Every syntactic element seems to be necessary; for example, replacing `if x.nil?` with `if x` results in expected behavior:

```
$ rubocop web.rb
Inspecting 1 file
E

Offenses:

web.rb:5:20: E: unexpected token kIF_MOD
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
      author: true if x,
                   ^^

1 file inspected, 1 offense detected
```

--------

## Expected behavior

Running rubocop on a file with a syntax error (see below) should show the parse error.

## Actual behavior

rubocop crashes with an exception

## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

```
$ cat web.rb
def func
  case true
  when true
    {
      author: true if x.nil?,
    }

    foo
  else
  end
end
$ bundle exec bin/rubocop  web.rb
Inspecting 1 file


0 files inspected, no offenses detected
undefined method `begin_pos' for nil:NilClass
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/source/range.rb:182:in `join'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/builders/default.rb:1191:in `join_exprs'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/builders/default.rb:1273:in `collection_map'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/builders/default.rb:1026:in `begin_body'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/ruby20.rb:3315:in `_reduce_9'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:259:in `_racc_do_parse_c'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:259:in `do_parse'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/base.rb:162:in `parse'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/base.rb:209:in `tokenize'
/home/nelhage/code/rubocop/lib/rubocop/processed_source.rb:99:in `tokenize'
/home/nelhage/code/rubocop/lib/rubocop/processed_source.rb:94:in `parse'
/home/nelhage/code/rubocop/lib/rubocop/processed_source.rb:36:in `initialize'
/home/nelhage/code/rubocop/lib/rubocop/processed_source.rb:17:in `new'
/home/nelhage/code/rubocop/lib/rubocop/processed_source.rb:17:in `from_file'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:334:in `get_processed_source'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:110:in `block in file_offenses'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:121:in `file_offense_cache'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:109:in `file_offenses'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:100:in `process_file'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:75:in `each'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:75:in `reduce'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:75:in `each_inspected_file'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:67:in `inspect_files'
/home/nelhage/code/rubocop/lib/rubocop/runner.rb:39:in `run'
/home/nelhage/code/rubocop/lib/rubocop/cli.rb:86:in `execute_runner'
/home/nelhage/code/rubocop/lib/rubocop/cli.rb:32:in `run'
bin/rubocop:13:in `block in <top (required)>'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
bin/rubocop:12:in `<top (required)>'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/nelhage/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/home/nelhage/.rbenv/versions/2.4/bin/bundle:23:in `load'
/home/nelhage/.rbenv/versions/2.4/bin/bundle:23:in `<main>'
```

## RuboCop version

Tested with latest master:
```
$ bundle exec bin/rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
$ git describe HEAD
v0.49.1-156-gc243880
```

as well as latest release:
```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
```

**Comment by Drenmi** [comment]
@nelhage-stripe: This looks like an upstream issue in [parser](https://github.com/whitequark/parser). Would you mind opening an issue there with your findings? 🙂

**Comment by nelhage-stripe** [comment]
@Drenmi Will do! `ruby-parse` handles the file fine, so I'd provisionally assigned blame to rubocop, but I can reproduce by writing some `parser` code myself. Will file over there.

**Comment by nelhage-stripe** [comment]
I bisected `parser`, and looks like https://github.com/whitequark/parser/issues/345 actually fixed this. Sorry for the noise!
