### ISSUE TITLE
RuboCop 0.50.0 crashes when trying to autocorrect a Style/SafeNavigation warning

### ISSUE THREAD

**Issue by smaximov** [bbatsov/rubocop#4741]
Minimal reproducible example (**test.rb**):

``` ruby
# frozen_string_literal: true

puts ARGV[0] && ARGV[0][/regexp/]
```

RuboCop config:

``` yml
AllCops:
  TargetRubyVersion: 2.4.2
```

## Steps to reproduce the problem

Run `$ rubocop -a test.rb`.

## Expected behavior

RuboCop corrects the warning, maybe producing something like this:

``` rb
# frozen_string_literal: true

puts ARGV[0]&.[](/regexp/)
```

## Actual behavior

RuboCop crashes with the following backtrace:

```
undefined method `begin' for nil:NilClass
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/parser-2.4.0.0/lib/parser/source/rewriter.rb:67:in `insert_before'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/corrector.rb:78:in `insert_before'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/style/safe_navigation.rb:99:in `block in autocorrect'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/corrector.rb:56:in `block (2 levels) in rewrite'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/parser-2.4.0.0/lib/parser/source/rewriter.rb:194:in `transaction'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/corrector.rb:55:in `block in rewrite'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/corrector.rb:53:in `each'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/corrector.rb:53:in `rewrite'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:126:in `autocorrect_all_cops'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:70:in `autocorrect'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:98:in `block in offenses'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:115:in `investigate'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:94:in `offenses'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:258:in `inspect_file'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:205:in `block in do_inspection_loop'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:237:in `block in iterate_until_no_changes'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:230:in `loop'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:121:in `file_offense_cache'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:100:in `process_file'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:75:in `each'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:75:in `reduce'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/runner.rb:39:in `run'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cli.rb:86:in `execute_runner'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/lib/rubocop/cli.rb:32:in `run'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/bin/rubocop:13:in `block in <top (required)>'
/Users/smaximov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/gems/rubocop-0.50.0/bin/rubocop:12:in `<top (required)>'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/bin/rubocop:23:in `load'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/bin/rubocop:23:in `<main>'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/bin/ruby_executable_hooks:15:in `eval'
/Users/smaximov/.rvm/gems/ruby-2.4.2@rubocop/bin/ruby_executable_hooks:15:in `<main>'
```

It works for usual method calls (`x && x.foo` &rarr; `x&.foo`) though.

## RuboCop version

```
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.4.2 x86_64-darwin16)
```

**Comment by smaximov** [comment]
Can be somehow related to #4731.

**Comment by tjchambers** [comment]
I am getting this as well on latest.
