### ISSUE TITLE
Lint/ReturnInVoidContext fails when there is a bare return in a script

### ISSUE THREAD

**Issue by davidk01** [bbatsov/rubocop#4800]
There seems to be an issue when a script just has a return statement that is not surrounded with any scoping construct like `def`, `begin`, etc. When the linter tries to find the ancestors it errors out because the first ancestor is `nil`.

A minimal reproducible case is to run rubocop on the following script

```ruby
return if true
```

The rubocop version I'm using is 0.50.0 and the relevant portion of the stack trace is

```bash
/Users/david.karapetyan/.rvm/gems/ruby-2.1.5/gems/rubocop-0.50.0/lib/rubocop/cop/lint/return_in_void_context.rb:48:in `method_name'
/Users/david.karapetyan/.rvm/gems/ruby-2.1.5/gems/rubocop-0.50.0/lib/rubocop/cop/lint/return_in_void_context.rb:37:in `on_return'
/Users/david.karapetyan/.rvm/gems/ruby-2.1.5/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:44:in `block (2 levels) in on_return'
/Users/david.karapetyan/.rvm/gems/ruby-2.1.5/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:111:in `with_cop_error_handling'
/Users/david.karapetyan/.rvm/gems/ruby-2.1.5/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:43:in `block in on_return'
/Users/david.karapetyan/.rvm/gems/ruby-2.1.5/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:42:in `each'
/Users/david.karapetyan/.rvm/gems/ruby-2.1.5/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:42:in `on_return'
/Users/david.karapetyan/.rvm/gems/ruby-2.1.5/gems/rubocop-0.50.0/lib/rubocop/ast/traversal.rb:133:in `on_if'
/Users/david.karapetyan/.rvm/gems/ruby-2.1.5/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:48:in `on_if'
```

The relevant method seems to be

```ruby
         def method_name(return_node)
           method_node = return_node.each_ancestor(:block, :def, :defs).first
           return nil unless method_node.def_type?
           method_node.children.first
         end
```

It is possible for `method_node = return_node.each_ancestor(:block, :def, :defs).first` to be `nil` and that's where the failure happens.

The file is `lib/rubocop/cop/lint/return_in_void_context.rb`

--------

## Expected behavior

I'm not sure what the expected behavior should be. I don't think there should be an exception and instead bare return expressions in scripts should be handled as if the entire script was the scope for it. Or maybe this is not an issue at all and we should just return `nil` when `method_name` is `nil`.

## Actual behavior

As you see above there is an exception raised because of `nil`.

## Steps to reproduce the problem

See the script above. Running rubocop on that script will reproduce the error on version 0.50.0.

## RuboCop version

```bash
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.1.5 x86_64-darwin14.0)
```

**Comment by davidk01** [comment]
Oh I see the issue is fixed on master: https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/lint/return_in_void_context.rb#L42
