### ISSUE TITLE
Rails/RedundantReceiverInWithOptions crashes rubocop for some inputs

### ISSUE THREAD

**Issue by aried3r** [bbatsov/rubocop#5226]
## Expected behavior

Should not abort with an error, possibly auto correct the code.

## Actual behavior

The following exception is thrown:

```
$ rubocop -a --only Rails/RedundantReceiverInWithOptions example.rb
Inspecting 1 file


0 files inspected, no offenses detected
undefined method `loc' for :to:Symbol
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb:69:in `block_argument_range'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb:62:in `block in autocorrect'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/corrector.rb:56:in `block (2 levels) in rewrite'
/2.4.2/lib/ruby/gems/2.4.0/gems/parser-2.4.0.2/lib/parser/source/rewriter.rb:198:in `transaction'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/corrector.rb:55:in `block in rewrite'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/corrector.rb:53:in `each'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/corrector.rb:53:in `rewrite'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:126:in `autocorrect_all_cops'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:70:in `autocorrect'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:98:in `block in offenses'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:115:in `investigate'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:94:in `offenses'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:258:in `inspect_file'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:205:in `block in do_inspection_loop'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:237:in `block in iterate_until_no_changes'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:230:in `loop'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:111:in `block in file_offenses'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:121:in `file_offense_cache'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:109:in `file_offenses'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:100:in `process_file'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:75:in `each'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:75:in `reduce'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:67:in `inspect_files'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:39:in `run'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cli.rb:128:in `execute_runner'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cli.rb:60:in `execute_runners'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cli.rb:31:in `run'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/bin/rubocop:13:in `block in <top (required)>'
/2.4.2/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/bin/rubocop:12:in `<top (required)>'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/dev/rubocop-issue/bin/rubocop:21:in `<top (required)>'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/command_wrapper.rb:40:in `call'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
-e:1:in `<main>'
```

## Steps to reproduce the problem

Run `rubocop -a --only Rails/RedundantReceiverInWithOptions example.rb`

```
# example.rb
require 'rails_helper'

RSpec.describe 'Example pages', type: :request do
  it 'checks things' do
    with_options scope: 'activerecord.attributes' do |i18n|
      expect(subject).to have_field i18n.t('foo.bar')
    end
  end
end
```

## RuboCop version

```
$ rubocop -V
0.52.0 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-darwin16)
```

**Comment by wata727** [comment]
I think that detection of this example code is due to false positives. If this auto-correction works correctly, it will be corrected as follows.

```ruby
require 'rails_helper'

RSpec.describe 'Example pages', type: :request do
  it 'checks things' do
    with_options scope: 'activerecord.attributes' do
      expect(subject).to have_field t('foo.bar')
    end
  end
end
```

But this is not the correct change. In this case, options are merged for unintended method invocation.


```ruby
require 'active_support'
require 'active_support/core_ext'

def self.options(opts = {})
  opts
end

with_options hello: :world do |merger|
  self.class     # => Object
  merger.options # => {:hello=>:world}
  options        # => {}
end

with_options hello: :world do
  self.class # => ActiveSupport::OptionMerger
  options    # => {:hello=>:world}
end
```
