### ISSUE TITLE
Exception in HeredocDelimiterNaming with offenses reported and exitcode 2

### ISSUE THREAD

**Issue by hurricup** [bbatsov/rubocop#5254]
`0.50.0 (using Parser 2.4.0.0, running on ruby 2.4.2 x86_64-darwin16)`

Exception:
```
/Users/annakutarba/.rvm/gems/ruby-2.4.0@diaspora20173/bin/ruby_executable_hooks:15:in `<main>'
An error occurred while Naming/HeredocDelimiterNaming cop was inspecting /Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/i18n-0.8.6/lib/i18n/gettext/po_parser.rb:295:12.
undefined method `captures' for nil:NilClass
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/cop/naming/heredoc_delimiter_naming.rb:49:in `delimiters'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/cop/naming/heredoc_delimiter_naming.rb:41:in `meaningful_delimiters?'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/cop/naming/heredoc_delimiter_naming.rb:33:in `on_heredoc'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/cop/mixin/heredoc.rb:10:in `on_str'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:44:in `block (2 levels) in on_dstr'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:111:in `with_cop_error_handling'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:43:in `block in on_dstr'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:42:in `each'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:42:in `on_dstr'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/ast/traversal.rb:101:in `block in on_send'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/ast/traversal.rb:99:in `each'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/ast/traversal.rb:99:in `each_with_index'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/ast/traversal.rb:99:in `on_send'
/Users/annakutarba/RubymineProjects/diaspora20173/vendor/bundle/ruby/2.4.0/gems/rubocop-0.50.0/lib/rubocop/cop/commissioner.rb:48:in `on_send'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
```

The problem that this version accepts only `\w` delimiters, but https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/naming/heredoc_delimiter_naming.rb#L50 supposes that there is not null match in the text.

And if it doesn't - rubocop exiting with error code 2. And some valid output if we've inspected a directory.

Unsure if this still may happen with current version of code.

**Comment by pocke** [comment]
Please give me a code to reproduce. And probably this problem has been fixed already in v0.52.0.
See https://github.com/bbatsov/rubocop/issues/4759 and https://github.com/bbatsov/rubocop/pull/4829

**Comment by hurricup** [comment]
https://github.com/svenfuchs/i18n/blob/master/lib/i18n/gettext/po_parser.rb

**Comment by pocke** [comment]
It looks fixed in 0.52.0. So I'll close this issue. Thank you for the feedback!


```bash
$ rubocop _0.50.0_ lib/i18n/gettext/po_parser.rb --cache false

...

18 errors occurred:
An error occurred while Naming/HeredocDelimiterCase cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:23:12.
An error occurred while Naming/HeredocDelimiterCase cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:235:12.
An error occurred while Naming/HeredocDelimiterCase cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:246:12.
An error occurred while Naming/HeredocDelimiterCase cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:264:12.
An error occurred while Naming/HeredocDelimiterCase cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:282:12.
An error occurred while Naming/HeredocDelimiterCase cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:295:12.
An error occurred while Naming/HeredocDelimiterCase cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:302:12.
An error occurred while Naming/HeredocDelimiterCase cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:309:12.
An error occurred while Naming/HeredocDelimiterCase cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:316:12.
An error occurred while Naming/HeredocDelimiterNaming cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:23:12.
An error occurred while Naming/HeredocDelimiterNaming cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:235:12.
An error occurred while Naming/HeredocDelimiterNaming cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:246:12.
An error occurred while Naming/HeredocDelimiterNaming cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:264:12.
An error occurred while Naming/HeredocDelimiterNaming cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:282:12.
An error occurred while Naming/HeredocDelimiterNaming cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:295:12.
An error occurred while Naming/HeredocDelimiterNaming cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:302:12.
An error occurred while Naming/HeredocDelimiterNaming cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:309:12.
An error occurred while Naming/HeredocDelimiterNaming cop was inspecting /home/pocke/ghq/github.com/svenfuchs/i18n/lib/i18n/gettext/po_parser.rb:316:12.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.50.0 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-linux)
```


```bash
$ rubocop _0.52.0_ lib/i18n/gettext/po_parser.rb --cache false
Inspecting 1 file
W

Offenses:

...


1 file inspected, 161 offenses detected
```

**Comment by hurricup** [comment]
I can see from sources that pattern was extended and now handles non-`\w` markers. Purpose of this issue was to put attention to the `match().captures()` part without nullability checking.

Again, I don't know internals enough to say if this still may happen in some other case, when match return nil.

**Comment by Drenmi** [comment]
I would prefer not to have a `nil` check for exactly this reason. If we have it fail silently on some edge case that we might not have considered, we likely will never find those, compared to if we fail nosily. 🙂
