### ISSUE TITLE
Performance/RegexpMatch - false positive Use match? instead of =~

### ISSUE THREAD

**Issue by davidhrbac** [bbatsov/rubocop#5257]
I'm aware of #5038. 

## Actual behavior

Have a validator from documentation http://edgeguides.rubyonrails.org/active_record_validations.html#validates-each

test.rb

```ruby
class Person < ApplicationRecord
  validates_each :name, :surname do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end
end
```

I have to change the line to 

```ruby
    record.errors.add(attr, 'must start with upper case') if value.match?(/\A[[:lower:]]/)
```

This change will lead to hidden bug which does not handle `nil` value. If the project does NOT rely on rspec tests, the bug is being silently introduced into production code. The code must be something like this:

```ruby
    record.errors.add(attr, 'must start with upper case') if value.to_s.match?(/\A[[:lower:]]/)
```

## Steps to reproduce the problem

```
rubocop test.rb
Inspecting 1 file
C

Offenses:

test.rb:3:62: C: Performance/RegexpMatch: Use match? instead of =~ when MatchData is not used.
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

```ruby
2.4.2 :003 > value = nil; puts 'ERROR' if value.match?(/\A[[:lower:]]/)
NoMethodError: undefined method `match?' for nil:NilClass
	from (irb):3
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /home/rails/scs-ror/bin/rails:9:in `<top (required)>'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/commands/rails.rb:6:in `call'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/command_wrapper.rb:38:in `call'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/rails/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/rails/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

2.4.2 :004 > value = nil; puts 'ERROR' if value.to_s.match?(/\A[[:lower:]]/)
 => nil 
```

In case the validator is based on unless the scenario is like this:

```ruby
2.4.2 :005 > value = "email@domain.tld"; puts 'ERROR' unless value.match?(/\A[a-z0-9][a-z0-9_\.\-\+]*@([a-z0-9\-]+\.)+[a-z]{2,}\z/i)
 => nil 

2.4.2 :006 > value = nil; puts 'ERROR' unless value.match?(/\A[a-z0-9][a-z0-9_\.\-\+]*@([a-z0-9\-]+\.)+[a-z]{2,}\z/i)
NoMethodError: undefined method `match?' for nil:NilClass
	from (irb):6
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /home/rails/scs-ror/bin/rails:9:in `<top (required)>'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/commands/rails.rb:6:in `call'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/command_wrapper.rb:38:in `call'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /home/rails/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/rails/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/rails/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

```

Converted to `to_s`:

```ruby
2.4.2 :007 > value = "email@domain.tld"; puts 'ERROR' unless value.to_s.match?(/\A[a-z0-9][a-z0-9_\.\-\+]*@([a-z0-9\-]+\.)+[a-z]{2,}\z/i)
 => nil 
2.4.2 :008 > value = nil; puts 'ERROR' unless value.to_s.match?(/\A[a-z0-9][a-z0-9_\.\-\+]*@([a-z0-9\-]+\.)+[a-z]{2,}\z/i)
ERROR
 => nil 
2.4.2 :009 > value = []; puts 'ERROR' unless value.to_s.match?(/\A[a-z0-9][a-z0-9_\.\-\+]*@([a-z0-9\-]+\.)+[a-z]{2,}\z/i)
ERROR
 => nil 
2.4.2 :010 > value = {}; puts 'ERROR' unless value.to_s.match?(/\A[a-z0-9][a-z0-9_\.\-\+]*@([a-z0-9\-]+\.)+[a-z]{2,}\z/i)
ERROR
 => nil 
```

## RuboCop version

```
$ rubocop -V
0.52.0 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-linux)
```

**Comment by pocke** [comment]
Maybe it duplicated with https://github.com/bbatsov/rubocop/issues/4298

**Comment by davidhrbac** [comment]
Maybe is it a regression? We have no warnings on that with rubocop < 0.52.0

**Comment by pocke** [comment]
> Maybe is it a regression? We have no warnings on that with rubocop < 0.52.0

Hmm, I can get the warning with rubocop 0.52.0 ~ 0.49.0.

`test.rb`

```ruby
record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
```

`.rubocop.yml`

```yaml
AllCops:
  TargetRubyVersion: 2.4
```

```bash
$ rubocop _0.49.0_ --only Performance/RegexpMatch
Inspecting 1 file
C

Offenses:

test.rb:1:58: C: Use match? instead of =~ when MatchData is not used.
record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected

$ rubocop _0.50.0_ --only Performance/RegexpMatch
Inspecting 1 file
C

Offenses:

test.rb:1:58: C: Use match? instead of =~ when MatchData is not used.
record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected


$ rubocop _0.51.0_ --only Performance/RegexpMatch
Inspecting 1 file
C

Offenses:

test.rb:1:58: C: Use match? instead of =~ when MatchData is not used.
record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected


$ rubocop _0.52.0_ --only Performance/RegexpMatch
Inspecting 1 file
C

Offenses:

test.rb:1:58: C: Performance/RegexpMatch: Use match? instead of =~ when MatchData is not used.
record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```
