### ISSUE TITLE
SystemStackError occurred at Docker image `ruby:2.5.0-alpine3.7`

### ISSUE THREAD

**Issue by koshigoe** [bbatsov/rubocop#5341]
Rubocop might not cause of this problem...

## Expected behavior

Nothing was raised.

## Actual behavior

`SystemStackError` exception occurred at Docker image `ruby:2.5.0-alpine3.7`.

## Steps to reproduce the problem

The code like a following:

```ruby
# sample.rb
require 'rails_helper'

RSpec.describe MyClass do
  describe '#my_method' do
    subject { MyClass.new.my_method(arg) }

    context 'when ...' do
      context 'when ...' do
        context 'when ...' do
          context 'when ...' do
            let(:arg) { create(:arg, :trait, attr: x) }

            it 'should be ...' do
              YourClass.new(x: X.x(y: Y.y(z: Z.z(a: A.a(b: B.b(c: C.c))))))
            end
          end
        end
      end
    end
  end
end
```

<details>
<summary>By ruby:2.5.0-alpine3.7</summary>

```
# 2.5.0/Dockerfile
FROM ruby:2.5.0-alpine3.7

RUN gem install rubocop -v 0.52.1
COPY sample.rb /sample.rb

CMD [ "rubocop", "-d", "/sample.rb" ]
```

```
$ docker build -t ruby:2.5.0-alpine3.7-sltd -f 2.5.0/Dockerfile .
$ docker container run --rm ruby:2.5.0-alpine3.7-sltd
For /: configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/default.yml
Inheriting configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/enabled.yml
Inheriting configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/disabled.yml
Inspecting 1 file
Scanning /sample.rb


0 files inspected, no offenses detected
Traceback (most recent call last):
        268: from /usr/local/bundle/bin/rubocop:23:in `<main>'
        267: from /usr/local/bundle/bin/rubocop:23:in `load'
        266: from /usr/local/bundle/gems/rubocop-0.52.1/bin/rubocop:12:in `<top (required)>'
        265: from /usr/local/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
        264: from /usr/local/bundle/gems/rubocop-0.52.1/bin/rubocop:13:in `block in <top (required)>'
        263: from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cli.rb:38:in `run'
        262: from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cli.rb:78:in `execute_runners'
        261: from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cli.rb:150:in `execute_runner'
         ... 256 levels...
          4: from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/variable_force.rb:85:in `catch'
          3: from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/variable_force.rb:87:in `block in process_node'
          2: from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/variable_force.rb:101:in `process_children'
          1: from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/node.rb:172:in `each_child_node'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/node.rb:172:in `each': stack level too deep (SystemStackError)
```
</details>

<details>
<summary>By ruby:2.4.3-alpine3.7</summary>

```
# 2.4.3/Dockerfile
FROM ruby:2.4.3-alpine3.7

RUN gem install rubocop -v 0.52.1
COPY sample.rb /sample.rb

CMD [ "rubocop", "-d", "/sample.rb" ]
```

```
$ docker build -t ruby:2.4.3-alpine3.7-sltd -f 2.4.3/Dockerfile .
$ docker container run --rm ruby:2.4.3-alpine3.7-sltd
For /: configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/default.yml
Inheriting configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/enabled.yml
Inheriting configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/disabled.yml
Inspecting 1 file
Scanning /sample.rb
.

1 file inspected, no offenses detected
Finished in 0.10488527800043812 seconds
```

</details>

<details>
<summary>By ruby:2.5.0-stretch</summary>

```
# 2.5.0-stretch/Dockerfile
FROM ruby:2.5.0-stretch

RUN gem install rubocop -v 0.52.1
COPY sample.rb /sample.rb

CMD [ "rubocop", "-d", "/sample.rb" ]
```

```
$ docker build -t ruby:2.5.0-stretch-sltd -f 2.5.0-stretch/Dockerfile .
$ docker container run --rm ruby:2.5.0-stretch-sltd
For /: configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/default.yml
Inheriting configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/enabled.yml
Inheriting configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/disabled.yml
Inspecting 1 file
Scanning /sample.rb
.

1 file inspected, no offenses detected
Finished in 0.11523672300063481 seconds
```

</details>

## RuboCop version

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.5.0 x86_64-linux)
```

**Comment by koshigoe** [comment]
Sorry, I think this is not Rubocop's issue.
I close this issue myself.

**Comment by jlfaber** [comment]
@koshigoe , I'm seeing something similar with 2.5.0-alpine.  Can you elaborate on what the root cause was?  Thanks!

**Comment by koshigoe** [comment]
I asked at Ruby's issue tracker. (in Japanese, sorry)
https://bugs.ruby-lang.org/issues/14387

But, it has not resolved yet.

**Comment by jlfaber** [comment]
Thanks!
