### ISSUE TITLE
Crash: undefined method `begin' for nil:NilClass

### ISSUE THREAD

**Issue by CloCkWeRX** [bbatsov/rubocop#5392]
```
undefined method `begin' for nil:NilClass
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parser-2.4.0.2/lib/parser/source/rewriter.rb:71:in `insert_before'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/corrector.rb:78:in `insert_before'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/style/safe_navigation.rb:99:in `block in autocorrect'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/corrector.rb:56:in `block (2 levels) in rewrite'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parser-2.4.0.2/lib/parser/source/rewriter.rb:198:in `transaction'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/corrector.rb:55:in `block in rewrite'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/corrector.rb:53:in `each'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/corrector.rb:53:in `rewrite'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:126:in `autocorrect_all_cops'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:70:in `autocorrect'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:98:in `block in offenses'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:115:in `investigate'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:94:in `offenses'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:258:in `inspect_file'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:205:in `block in do_inspection_loop'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:237:in `block in iterate_until_no_changes'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:230:in `loop'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:121:in `file_offense_cache'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:100:in `process_file'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:75:in `each'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:75:in `reduce'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/runner.rb:39:in `run'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cli.rb:86:in `execute_runner'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/lib/rubocop/cli.rb:32:in `run'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/bin/rubocop:13:in `block in <top (required)>'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.50.0/bin/rubocop:12:in `<top (required)>'
/Users/dan/.rbenv/versions/2.3.1/bin/rubocop:23:in `load'
/Users/dan/.rbenv/versions/2.3.1/bin/rubocop:23:in `<top (required)>'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/Users/dan/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/dan/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by pocke** [comment]
Duplicated, and this bug has been fixed in #4749 .
Please try using v0.51.0 or newer (latest version is v0.52.1). Feel free reopen the issue if the issue still exists for your code.
