### ISSUE TITLE
undefined method `source' for nil:NilClass

### ISSUE THREAD

**Issue by jcoyne** [bbatsov/rubocop#5497]
```
bundle exec rubocop -d app/presenters/blacklight/facet_field_presenter.rb
For /Users/jcoyne/workspace/projectblacklight/blacklight: configuration from /Users/jcoyne/workspace/projectblacklight/blacklight/.rubocop.yml
configuration from /Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-rspec-1.22.1/config/default.yml
configuration from /Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-rspec-1.22.1/config/default.yml
Default configuration from /Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/config/default.yml
Inheriting configuration from /Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/config/enabled.yml
Inheriting configuration from /Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/config/disabled.yml
Inheriting configuration from /Users/jcoyne/workspace/projectblacklight/blacklight/.rubocop_todo.yml
Inspecting 1 file
Scanning /Users/jcoyne/workspace/projectblacklight/blacklight/app/presenters/blacklight/facet_field_presenter.rb
An error occurred while Rails/Presence cop was inspecting /Users/jcoyne/workspace/projectblacklight/blacklight/app/presenters/blacklight/facet_field_presenter.rb:42:6.
undefined method `source' for nil:NilClass
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/rails/presence.rb:113:in `replacement'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/rails/presence.rb:107:in `message'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/rails/presence.rb:76:in `block in on_if'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/rails/presence.rb:45:in `redundant_receiver_and_other'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/rails/presence.rb:74:in `on_if'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:44:in `block (2 levels) in on_if'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:109:in `with_cop_error_handling'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:43:in `block in on_if'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:42:in `each'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:42:in `on_if'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `block in on_begin'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `each'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `on_begin'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_begin'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:95:in `on_def'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_def'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `block in on_begin'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `each'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `on_begin'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_begin'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:88:in `on_class'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_class'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:141:in `on_while'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_module'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:12:in `walk'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:114:in `investigate'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:102:in `offenses'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:258:in `inspect_file'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:205:in `block in do_inspection_loop'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:237:in `block in iterate_until_no_changes'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:230:in `loop'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:121:in `file_offense_cache'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:100:in `process_file'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `each'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `reduce'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:39:in `run'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cli.rb:150:in `execute_runner'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cli.rb:78:in `execute_runners'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cli.rb:38:in `run'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/bin/rubocop:13:in `block in <top (required)>'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/bin/rubocop:12:in `<top (required)>'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bin/rubocop:23:in `load'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bin/rubocop:23:in `<top (required)>'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/Users/jcoyne/.rbenv/versions/2.4.2/bin/bundle:30:in `block in <main>'
/Users/jcoyne/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/Users/jcoyne/.rbenv/versions/2.4.2/bin/bundle:22:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Rails/Presence cop was inspecting /Users/jcoyne/workspace/projectblacklight/blacklight/app/presenters/blacklight/facet_field_presenter.rb:42:6.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-darwin16)
Finished in 1.6911879999679513 seconds
```

**Comment by jcoyne** [comment]
The code that triggers this error seems to be:
```ruby
return false unless present?
```

or 
```ruby
return false if blank?
```

**Comment by pocke** [comment]
It has been fixed in master. https://github.com/bbatsov/rubocop/pull/5385
