### ISSUE TITLE
invalid option: - 'Rakefile'

### ISSUE THREAD

**Issue by denisoster** [bbatsov/rubocop#5880]
- Ruby 2.5.1
- Rails 5.2.0
- RuboCop 0.55.0

```
[denis@thinkpad portal]$ bundle exec rubocop
invalid option: - 'Rakefile'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-0.55.0/lib/rubocop/options.rb:21:in `parse'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-0.55.0/lib/rubocop/cli.rb:37:in `run'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-0.55.0/bin/rubocop:13:in `block in <top (required)>'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-0.55.0/bin/rubocop:12:in `<top (required)>'
/home/denis/.asdf/installs/ruby/2.5.1/bin/rubocop:23:in `load'
/home/denis/.asdf/installs/ruby/2.5.1/bin/rubocop:23:in `<top (required)>'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/denis/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
```

**Comment by mikegee** [comment]
I can't duplicate this yet. What are the contents of your `RUBOCOP_OPTS` environment variable?

**Comment by denisoster** [comment]
@mikegee [.rubocop](https://gist.github.com/denisoster/1433efd6a478df09ae2e1b675477ccaf)
What do you need to do to see `RUBOCOP_OPTS`?

**Comment by mikegee** [comment]
> What do you need to do to see `RUBOCOP_OPTS`?

`echo $RUBOCOP_OPTS` from your shell.

**Comment by mikegee** [comment]
Was that really the content of a file called `.rubocop`? It looks a lot more like a `.rubocop.yml`.

**Comment by denisoster** [comment]
@mikegee 
![image](https://user-images.githubusercontent.com/15886355/40002559-c59a8d6e-5799-11e8-8f2c-138ca9f6e00c.png)
Yes `.rubocop.yml`

**Comment by denisoster** [comment]
@mikegee yes. `.rubocop` does not exist.

**Comment by mikegee** [comment]
Welp, this makes no sense then. You reported a failure to handle a command line option of "Rakefile", but you are not passing that option in [the three places](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/options.rb#L20) Rubocop pulls from: `.rubocop` file, `ENV['RUBOCOP_OPTS']`, and the command line itself. 🤔
